libs/components/src/constants/navigation.ts
=> [Test Feedback Fix] 마이페이지 레이아웃 피드백 반영

libs/components/src/lib/SignupForm.tsx
=> [Test Feedback Fix]seller 회원가입 테스트 피드백 수정

apps/overlay-controller/src/lib/admin.js
- 비회원 체크박스 메세지 전송시 로그인 state 바뀌지 않는 현상 수정
- 접속된 클라이언트 확인 버그 수정
=> 비회원 체크박스 버그 수정 / 접속된 클라이언트 확인 버그 수정

libs/components/src/lib/GoodsRegistCommonInfo.tsx, libs/components/src/lib/GoodsRegistDescription.tsx, libs/hooks/src/lib/s3.tsx
수정사항
- 상품 이미지 s3 업로드시 public-read로 설정
- 상품공통정보 새로 입력시 공통정보명 입력하지 않으면 입력하라는 토스트 추가
- 상품공통정보, 상세정보 텍스트에디터에 list 버튼 추가
=> [마이페이지 - 상품] 상품 등록 - 상품 이미지 s3 업로드시 public-read로 설정

libs/components/src/lib/GoodsRegistCommonInfo.tsx, libs/components/src/lib/GoodsRegistDataOptions.tsx, libs/components/src/lib/GoodsRegistForm.tsx, libs/components/src/lib/SocialAccountUnlinkBox.tsx, libs/components/src/lib/StockInfoButton.tsx
=> 1차스프린트 내부 시연회 후 피드백 수정사항

libs/components/src/lib/BusinessRegistrationDialog.tsx
기존 완료된 일감에서 테스트 중 나온 오류 수정
- dev로 merge된 후, dev에 대한 수정을 위한 임시 브랜치 생성
=> [Fix] 관리자 페이지 통신판매업신고증 다운로드 수정

libs/components/src/lib/LiveShoppingList.tsx, libs/components/src/lib/LiveShoppingRegistRequestField.tsx
- 요청사항 500자 고지 문구 추가
- 요청사항 500자 초과시 에러 문구 추가
- 등록된 라이브 쇼핑 없을 때, "라이브 쇼핑 등록해주세요" 문구 테이블 안으로 이동
=> [버그수정] 라이브 쇼핑 등록 버그 수정

libs/components/src/lib/BusinessRegistrationForm.tsx, libs/components/src/lib/ShopNameDialog.tsx, libs/components/src/lib/admin/AdminGoodsConfirmationDialog.tsx
- 사업자등록정보 입력
- 상점명 입력
- 상품 등록 입력
=> [기능 수정] inputRef 사용 오류 수정

libs/nest-modules/src/lib/overlay/overlay.service.ts
=> [수정] 오버레이 서버 aws-sdk 버전 변경

libs/components/src/lib/admin/AdminImageDownloadButton.tsx, libs/hooks/src/lib/s3.tsx, package.json, yarn.lock
1. 사업자등록증, 통장사본, 통신판매신고증 이미지 업로드 변경
2. 관리자 페이지 상에서 이미지 다운로드 변경
=> [기능 변경] 정산정보 S3 라이브러리 변경

apps/admin/pages/settlement/index.tsx, apps/api/src/settings/appSetting.ts, apps/web/pages/_app.tsx, libs/components/src/lib/ChakraDataGrid.tsx, libs/components/src/lib/MypageNoticeSection.tsx, libs/components/src/lib/OrderList.tsx, libs/components/src/lib/SellerGoodsList.tsx, libs/components/src/lib/admin/AdminAccountList.tsx, libs/components/src/lib/admin/AdminBusinessRegistrationList.tsx, libs/components/src/lib/admin/AdminGiftList.tsx, libs/components/src/lib/admin/AdminNoticeSection.tsx, libs/components/src/lib/settlement/AdminSettlementDoneList.tsx, libs/components/src/lib/settlement/SettlementInfoDialog.tsx, libs/components/src/lib/settlement/SettlementList.tsx, libs/components/src/lib/settlement/SettlementTargetList.tsx, libs/firstmall-db/src/lib/fm-settlemenets/fm-settlements.service.ts, libs/nest-modules/src/lib/seller/seller-settlement.service.ts, libs/shared-types/src/index.ts, libs/shared-types/src/lib/constants/fmOrderPayments.ts, libs/shared-types/src/lib/res-types/fmSettlements.res.ts, libs/utils/src/index.ts, libs/utils/src/lib/calcPgCommission.ts
- 정산 실행되지 않는 버그수정
- 관라지페이지 정산 실행 이전 확인에 내용 추가
- fm_order.payment 한글화 적용
- ChakraDataGrid 컴포넌트 border 일괄 적용 및 테마에 따른 보더컬러 일괄 적용
=> Add: 정산처리 수정사항 반영, ChakraDataGrid 테마관련수정

libs/components/src/lib/ChakraDataGrid.tsx, libs/components/src/lib/ExportDetailSummary.tsx, libs/components/src/lib/MainBeta.tsx, libs/components/src/lib/SellerGoodsList.tsx
Fix: ChakraDataGrid 다크테마 스타일 수정
Fix: 메인 유튜브 영상 검은화면 안보이도록 수정
=> Hwasurr css fixes

libs/components/src/lib/ChakraDataGrid.tsx, libs/components/src/lib/GoodsRegistPictures.tsx, libs/components/src/lib/OrderCancelRequestDialog.tsx, libs/components/src/lib/OrderList.tsx, libs/components/src/lib/SellerGoodsList.tsx, libs/nest-modules/src/lib/order-cancel/order-cancel.controller.ts, libs/prisma-orm/prisma/dummyData.ts, libs/prisma-orm/prisma/schema.prisma, libs/prisma-orm/prisma/seed.ts, libs/shared-types/src/lib/constants/signupRegisterOptions.ts
=> 개발자간 통합테스트 후 수정사항

libs/components/src/lib/GoodsRegistForm.tsx, libs/components/src/lib/admin/AdminGiftList.tsx, libs/components/src/lib/admin/AdminLiveShoppingList.tsx, libs/firstmall-db/src/lib/fm-orders/fm-orders.controller.ts, libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts, libs/firstmall-db/src/lib/fm-orders/utills/statCounter.ts, libs/hooks/src/lib/s3.tsx
1. 마이페이지 - 요약지표 : 매출 확인에 대해서 결제 확인(25) 추가
2. 주문 검색 시 쿼리 문법 에러 수정
3. 상품 이미지 등록시 S3 버전 호환에 대한 수정
4. 마이페이지 - 요약지표: 주문 상품별 상태 적용을 위한 쿼리 변경
5. 관리자페이지 - 선물하기 리스트 : 판매시작시각 - 판매종료시각으로 조건 변경
=> [버그 수정] 통합 테스트 후 수정사항

libs/components/src/lib/ExportDialog.tsx, libs/components/src/lib/ExportManyDialog.tsx
- 출고처리 다이얼로그 x 버튼 눌러서 닫을 때 resetSelectedOrderShippings 을 실행하지 않아서 orderShipping 누적되는 문제 수정
- 단일출고처리 다이얼로그에서 합포장 버튼 활성화 기준 order.shippings.length >= 2 추가
=> [버그수정] 출고처리 다이얼로그 

apps/admin/pages/live-shopping/[liveShoppingId].tsx
- 등록된 방송인 없는경우 userNickname 불러오지 못하는 경우 에러발생하는 부분 수정
- textarea readonly 속성 추가
=> 관리자페이지 라이브쇼핑 상세보기 화면

apps/web/next-sitemap.js, apps/web/pages/404.tsx, apps/web/pages/_app.tsx, apps/web/pages/_document.tsx, aws-cdk/lib/prod/app-stack.ts, libs/components/src/lib/KksLogo.tsx, package.json, tools/ignore-admin-vercel-build.sh, tools/ignore-vercel-build.sh, workspace.json, yarn.lock
기본적 SEO, 서치콘솔, 웹마스터 도구 추가 작업 및 배포 비 효율성 제거 작업
- sitemap 생성 스크립트 추가 (`yarn nx run web:postbuild`)
- vercel build script에 sitemap 생성 스크립트 실행하도록 수정
- preview 브랜치 (dev, master를 제외한 모든 브랜치) 로부터의 build 는 무시하도록 ignore-build 쉘 스크립트 수정
- 다음 사이트 등록
- 네이버 웹마스터도구 사이트 등록
- 구글 웹마스터 도구 사이트 등록
패키지 설치
- next-seo
- next-sitemap (devDependencies)
=> 기본적 SEO, 서치콘솔, 웹마스터 도구 추가 작업 및 배포 비 효율성 제거 작업

libs/components/src/lib/ExportOrderOptionList.tsx
=> [판매자센터] 주문페이지 - 출고처리 다이얼로그에 배송메모 표시(워커님 피드백)

libs/prisma-orm/prisma/migrations/20211206080750_/migration.sql, libs/prisma-orm/prisma/schema.prisma
- 이전 로그인 구현시 판매자의 로그인 로직을 동일하게 사용, 히스토리 또한 동일하게 사용하도록 구현
- 로그인 히스토리를 위한 인덱스 추가
=> [기능 구현] 로그인 히스토리 구현

apps/admin/pages/live-shopping/[liveShoppingId].tsx, libs/components/src/lib/admin/AdminOverlayImageUploadDialog.tsx, libs/nest-modules/src/lib/admin/admin.service.ts
- broadcaster mail을 받아오지 않아 null에러 뜨는 현상 수정
=> [버그수정] 관리자 페이지 - 오버레이 이미지 등록 버그수정

apps/web-broadcaster-center/pages/mypage/index.tsx, libs/components/src/lib/BroadcasterLiveShoppingList.tsx, libs/components/src/lib/BroadcasterStatusSection.tsx, libs/components/src/lib/CanScrollableText.tsx, libs/components/src/lib/MypageLiveShoppingSection.tsx, libs/components/src/lib/MypageNoticeSection.tsx, libs/components/src/lib/StartGuideCard.tsx, libs/components/src/lib/settlement/SettlementList.tsx
#155 머지 이후 #158 머지하여 이 풀리퀘스트 적용안됨
=> Fix: 메인화면 레이아웃 배치 수정

apps/web-broadcaster-center/pages/mypage/index.tsx
- 시작가이드의 조건이 제대로 정의되지 않아 연락처가 저장되었음에도 열리는 문제 해결
=> [Fix] 시작 가이드 열리는 조건 수정

libs/components/src/lib/AvatarChangeButton.tsx, libs/components/src/lib/LoginForm.tsx, libs/hooks/src/index.ts, libs/hooks/src/lib/mutation/useAvatarMutation.tsx, libs/nest-modules/src/lib/broadcaster/broadcaster.controller.ts, libs/nest-modules/src/lib/broadcaster/broadcaster.module.ts, libs/nest-modules/src/lib/broadcaster/broadcaster.service.ts, libs/nest-modules/src/lib/s3/s3.service.ts, libs/nest-modules/src/lib/seller/seller.service.ts
방송인도 판매자와 동일하게 프로필 사진 변경할 수 있도록 수정
=> 방송인 프로필 사진 변경

apps/overlay-controller/src/app/app.controller.ts, apps/overlay-controller/src/assets/layout.css, apps/overlay-controller/src/lib/admin.js, apps/overlay-controller/src/views/index.hbs, apps/overlay/src/app/app.gateway.ts, apps/overlay/src/app/app.screen.gateway.ts, apps/overlay/src/lib/overlayClient.js, libs/nest-modules/src/lib/overlay-controller/overlay-controller.service.ts, libs/nest-modules/src/lib/overlay/overlay.service.ts, libs/shared-types/src/index.ts, libs/shared-types/src/lib/dto/liveShopping.dto.ts, libs/shared-types/src/lib/dto/liveShoppingPurchaseMessage.dto.ts, libs/shared-types/src/lib/overlay/overlay-types.ts, libs/shared-types/src/lib/res-types/overlayControllerMain.res.ts
=> [오버레이 | 오버레이 컨트롤러] 메세지 삭제 기능 및 기타 기능 추가

apps/admin/pages/live-shopping/[liveShoppingId].tsx, apps/overlay-controller/src/assets/layout.css, apps/overlay-controller/src/lib/admin.js, apps/overlay-controller/src/views/index.hbs, apps/overlay/src/lib/overlayClient.js, libs/components/src/lib/BroadcasterLiveShoppingList.tsx, libs/components/src/lib/LiveShoppingDetailDialog.tsx, libs/components/src/lib/LiveShoppingList.tsx, libs/components/src/lib/admin/AdminOverlayImageUploadDialog.tsx, libs/nest-modules/src/lib/live-shopping/live-shopping.service.ts, libs/shared-types/src/lib/dto/liveShopping.dto.ts, libs/shared-types/src/lib/res-types/overlayControllerMain.res.ts
- 데이터 없을 때, dialog에서 null에러 뜨는 현상 수정
- 도네이션 이미지 용량 20MB로 변경
- form 제출 이후, 입력칸 비우기
- 파일 확장자 관계없이 세로배너/도네이션 이미지 렌더링 되도록 수정
- 라이브 쇼핑 목록에서 상품명, 방송시간 알 수 있도록 수정
- 테이블 렌더링 방식 수정
=> [버그수정] 테스트 중 나온 버그 수정

libs/components/src/lib/AvatarChangeButton.tsx, libs/components/src/lib/BroadcasterChannelSection.tsx, libs/components/src/lib/BroadcasterContact.tsx, libs/components/src/lib/BroadcasterImageUploadGuideDialog.tsx
- 크크쇼 정산 정보
- 크크쇼 방송인 계정 설정
- 크크쇼 방송인 센터 아바타 이미지
=> 3차 스프린트 개발자간 통합테스트 이후 수정

libs/components/src/lib/BroadcasterLiveShoppingList.tsx, libs/components/src/lib/ImageInput.tsx, libs/components/src/lib/admin/AdminOverlayImageUploadDialog.tsx, libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts, libs/utils-s3/src/lib/s3.ts
- [regist_date] 구매현황  regist_date 기준 정렬
=> [수정] 통합테스트 이후 수정 사항

libs/components/src/constants/contractTerms.ts, libs/components/src/lib/AvatarChangeButton.tsx, libs/components/src/lib/BroadcasterAddress.tsx, libs/components/src/lib/BroadcasterChannelSection.tsx, libs/components/src/lib/BroadcasterContact.tsx, libs/components/src/lib/BroadcasterImageUploadGuideDialog.tsx, libs/components/src/lib/BroadcasterLiveShoppingList.tsx, libs/components/src/lib/ImageInput.tsx, libs/components/src/lib/StartGuideCard.tsx, libs/components/src/lib/admin/AdminOverlayImageUploadDialog.tsx, libs/components/src/lib/guide/ContractionAgreementSection.tsx, libs/components/src/lib/settlement/BcSettlementHistory.tsx, libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts, libs/nest-modules/src/lib/admin/admin.controller.ts, libs/utils-s3/src/lib/s3.ts
- 시작가이드 명 온애드 -> 크크쇼
- 이용동의 전체 동의 가능하도록 + 읽지않아도 동의가능하도록
- 샘플및선물수령주소 포커스 가져오기
- 방송인 정산 내역 가독성 향상
-  admin ip 콘솔 확인 추가
=> 통합테스트 수정사항 적용

libs/nest-modules-auth/src/social/social-login-exception.filter.ts
- 소셜로그인 중 네이버 로그인 동의화면에서 '취소' 눌렀을 때 로그인 페이지로 이동하지 않고 에러메시지 표시되는 문제 해결(로그인 페이지로 이동하도록 수정함)
=> [fix] 소셜로그인 동의화면에서 '취소' 눌렀을때 잘못된 페이지로 이동하는 현상 수정

libs/components-seller/src/lib/LiveShoppingRegistForm.tsx
=> feat(seller): 라이브 쇼핑 등록 - 희망판매수수료 안내문구 추가

apps/web-seller/pages/mypage/live/index.tsx, libs/components-seller/src/lib/LiveShoppingList.tsx, libs/components-shared/src/lib/MypageBreadCrumb.tsx, libs/components-web-bc/src/lib/BroadcasterLiveShoppingList.tsx, libs/components-web-bc/src/lib/BroadcasterPurchaseList.tsx
=> refactor: 모바일 레이아웃 변경

libs/utils-frontend/src/lib/createChakraTheme.ts
- hover, border-radius, color 변경
- dark mode, white mode 따로 적용
=> feat: 스크롤바 css 적용

apps/admin/pages/seller/business-registration.tsx, libs/components-admin/src/lib/AdminBusinessRegistrationConfirmationDialog.tsx, libs/components-admin/src/lib/AdminBusinessRegistrationList.tsx, libs/components-admin/src/lib/AdminGoodsConfirmationDialog.tsx, libs/components-admin/src/lib/AdminGoodsList.tsx, libs/nest-modules-admin/src/admin/admin.service.ts
=> feat(admin): 이용동의 안한 판매자 상품검수, 사업자등록증 검수 통과 불가

libs/components-shared/src/lib/MypageLayout.tsx
=> fix: [BUG] 전체알림 페이지에 들어가면 사이드바가 판매자의 것으로 고정됨 #225

libs/nest-core/src/lib/interceptors/http-cache.interceptor.ts
=> fix: #238 redis 캐시 null 에러 수정

apps/web-seller/pages/mypage/orders/[orderId].tsx, libs/components-seller/src/lib/OrderDetailGoods.tsx, libs/components-shared/src/lib/SellTypeBadge.tsx, libs/firstmall-db/src/lib/fm-orders/fm-orders.controller.ts, libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts, libs/nest-modules-liveshopping/src/live-shopping/live-shopping.service.ts, libs/nest-modules-seller/src/seller/seller-product-promotion.service.ts, libs/prisma-orm/prisma/migrations/20220207072059_/migration.sql, libs/prisma-orm/prisma/schema.prisma, libs/shared-types/src/lib/res-types/fmOrder.res.ts
1. 매 상품마다 여러번 상품홍보, 라이브쇼핑 DB에 접근하는 방식에서 한번에 모든 상품홍보, 라이브쇼핑을 불러오는 방식으로 수정
2. 상품 판매 유형 정보를 따로 찾아내는 방식에서 주문상품정보 객체내에서 접근하는 방식으로 변경
---
refactor: SellType 이넘 값 수정
adc3d69
broadcasterPromotionPage -> productPromotion
=> refactor: 주문 상품 판매유형 조회 방식 변경

libs/components-web-bc/src/lib/PromotionPageUrlCard.tsx
판매자센터 방송홍보페이지 안내가이드 모달 내 배너 이미지 수정
=> [fix] 방송홍보페이지 안내문 더미 배너 수정

apps/overlay/src/app/app.controller.ts, libs/components-admin/src/lib/AdminLoginForm.tsx, libs/components-shared/src/lib/ProfileBox.tsx, libs/hooks/src/index.ts, libs/hooks/src/lib/queries/useHealthCheck.tsx, libs/nest-modules-auth/src/auth/auth.controller.ts, libs/nest-modules-broadcaster/src/broadcaster/broadcaster.controller.ts, libs/nest-modules-seller/src/seller/seller.controller.ts
커밋메시지 참조
추가사항
MVC - 동일 로직 공유 하는 두 렌더링 함수 리팩터링 f760c81
유저를 찾지 못한 경우 에러 코드 반환 404(Page Not Found) -> 400(Bad Request) 1149604
=> 관리자 버그 수정사항 + 배포 이후 처리사항

.commitlintrc, aws-cdk/lib/env-agnostic/domain-stack.ts, aws-cdk/lib/prod/app-stack.ts
- 오버레이 컨트롤러서버 환경변수 올바르게 주입
- 오버레이 컨트롤러서버 레코드 생성
- ALB 오버레이 서버 타겟그룹 수정 live 허용
fixes #257
=> ci: 배포 수정사항

apps/overlay-controller/src/app/app.controller.ts, apps/overlay-controller/src/assets/layout.css, apps/overlay-controller/src/lib/admin.js, apps/overlay-controller/src/views/index.hbs, libs/nest-modules-liveshopping/src/index.ts
- 총 주문금액
- 주문건수
- 선물건수
- 추가주문건수
=> feat: 오버레이 컨트롤러 간단한 대시보드 추가

libs/nest-core/src/lib/settings/cors.options.ts
CORS white list 에 크크쇼닷컴 추가안되어있는 오류 수정 `www.크크쇼`
=> feat: update cors option to allow kkshow main

apps/web-kkshow/pages/index.tsx, libs/components-web-kkshow/src/lib/main/KkshowMainBestBroadcaster.tsx, libs/components-web-kkshow/src/lib/main/KkshowMainPlusFriend.tsx, libs/components-web-kkshow/src/lib/main/carousel/KkshowMainCarouselContents.tsx
upcoming, simplebanner 캐러셀 클릭시 링크 추가
ISR 에러처리 추가
=> Hwasurr kkshow main fixes

libs/components-admin/src/lib/AdminAccountList.tsx, libs/components-admin/src/lib/AdminBusinessRegistrationConfirmationDialog.tsx, libs/components-admin/src/lib/AdminBusinessRegistrationList.tsx, libs/components-admin/src/lib/AdminGoodsConfirmationDialog.tsx, libs/components-admin/src/lib/AdminImageDownloadButton.tsx, libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts, libs/hooks/src/lib/queries/useAdminLiveShoppingList.tsx, libs/nest-modules-admin/src/admin/admin.service.ts
- 판매자 사업자등록증 등 이미지 다운로드 정상화
- 이용동의 값 제대로 못 받아오던 부분 수정
- 라이브쇼핑 목록 못 불러오던 부분 수정
=> fix: seller email 없어져서 발생한 에러들 수정

libs/components-admin/src/lib/AdminBusinessRegistrationList.tsx, libs/nest-modules-admin/src/admin/admin.service.ts
=> feat(admin): 사업자 등록증 검수 후에도 목록에 표시 / 필터링 적용

apps/overlay-controller/Dockerfile, apps/overlay/Dockerfile, libs/shared-types/src/index.ts, libs/shared-types/src/lib/res-types/searchResult.res.ts
[크크쇼] 검색결과 데이터 형태 정의
방송인
이미지, 이름, 링크, ...
상품
이미지, 이름, 링크, ...
라이브컨텐츠 ( 유튜브 VOD → 임베드X, 썸네일 또는 라이브쇼핑홍보이미지 )
이미지, 이름, 링크, ...
=> feat: 검색 결과 타입 추가

apps/web-kkshow/pages/index.tsx, libs/components-constants/src/lib/quickMenu.ts, libs/components-shared/src/lib/KksshowBottomQuickMenu.tsx
=> feat(kkshow) : 모바일 환경 하단 퀵메뉴 생성

apps/web-kkshow/pages/index.tsx, libs/components-shared/src/lib/BottomQuickMenu.tsx
- quick menu 반복문 unique key warning 뜨는 현상 수정
- quickmene 파일명 변경
=> fix: quick menu warning 뜨는 현상 수정 및 파일명 변경

libs/components-admin/src/lib/AdminBroadcasterProductPromotionSection.tsx, libs/components-seller/src/lib/BusinessRegistrationDialog.tsx
#292
- [관리자] 상품홍보아이템 생성 폼 validation오류 수정
- [판매자] 사업자등록증 입력폼에서 통신판매업신고증 필수 업로드 아님에도 오류문구 출력 & 제출 안되는 문제 수정
=> [fix] 버그 제보(#292) 수정 

aws-cdk/lib/prod/private-app-stack.ts
- 로드밸런서 라우팅 조건 오타 수정
Fixes #309 
인프라문제이므로 병합만으로 해결되지 않음. cdk deploy 실행 필요
-> 실행완료
=> fix: 프로덕션 메일러 전송되지 않는 버그 수정

libs/components-shared/src/lib/KksLogo.tsx, libs/components-web-kkshow/src/lib/GoodsDisplay.tsx, libs/components-web-kkshow/src/lib/GoodsReviewDisplay.tsx, libs/components-web-kkshow/src/lib/shopping/ShoppingEventBanner.tsx, libs/components-web-kkshow/src/lib/shopping/ShoppingGoodsOfTheWeek.tsx, libs/components-web-kkshow/src/lib/shopping/ShoppingKeywords.tsx
- 키워드 클릭시 `search?keyword=선택한키워드` 로 이동되도록 처리
- 크크쇼로고 오타로 불러오지 못하는 버그 수정
- 크크쇼 쇼핑탭 상품이미지 hover 애니메이션 추가
=> Hwasurr shopping tab fixes

apps/admin/pages/broadcaster/promotion-page/[promotionPageId].tsx, libs/components-admin/src/lib/AdminBroadcasterProductPromotionSection.tsx, libs/firstmall-db/src/lib/fm-exports/fm-exports.service.spec.ts, libs/firstmall-db/src/lib/fm-orders/fm-orders.service.spec.ts, libs/nest-modules-admin/src/admin/admin.service.ts, libs/nest-modules-broadcaster/src/broadcaster/broadcaster-promotion-page.service.ts, libs/nest-modules-product-promotion/src/lib/product-promotion.module.ts, libs/nest-modules-product-promotion/src/lib/product-promotion.service.ts, libs/shared-types/src/lib/dto/broadcasterProductPromotion.dto.ts
라이브쇼핑에 진행할 방송인 선택시 라이브쇼핑 상품이 방송인의 상품홍보페이지에 등록
테스트케이스
=> [관리자] 라이브쇼핑 진행할 방송인 선택시 상품홍보가 등록되도록 구성 

apps/admin/pages/customer/coupon/[couponId].tsx, libs/components-admin/src/lib/AdminCouponList.tsx, libs/components-admin/src/lib/AdminCreateCouponDialog.tsx, libs/hooks/src/lib/mutation/useAdminCouponMutation.tsx, libs/hooks/src/lib/mutation/useAdminCustomerCouponMutation.tsx, libs/nest-modules-admin/src/admin/admin-customer-coupon.controller.ts, libs/nest-modules-coupon/src/lib/coupon-log.service.ts, libs/nest-modules-coupon/src/lib/customer-coupon.service.ts, libs/nest-modules-order/src/lib/order.service.ts, libs/shared-types/src/lib/dto/customerCoupon.dto.ts
=> Fix: 관리자 - 할인쿠폰 관리 버그 수정

apps/overlay-controller/src/lib/admin.js, apps/overlay-controller/src/views/index.hbs, apps/overlay/src/app/app.screen.gateway.ts, apps/overlay/src/assets/layout.css, apps/overlay/src/lib/overlayClient.js
=> feat: 버추얼 캐릭터 영상 재생 기능

apps/overlay-controller/src/lib/admin.js, apps/overlay-controller/src/views/index.hbs, apps/overlay/src/app/app.screen.gateway.ts, apps/overlay/src/lib/overlayClient.js, libs/shared-types/src/lib/overlay/overlay-types.ts
=> feat: 소리 없는 뉴스 배너 기능

apps/overlay-controller/src/app/app.controller.ts, apps/overlay-controller/src/app/forbidden.exception.ts, aws-cdk/lib/dev/app-stack.ts, aws-cdk/lib/prod/app-stack.ts
로그인 기능 추가로 인해 GET `/` 시, 302 Redirect 로 응답되어 health-check 통과하지 못해 서버가 지속적으로 꺼지고, 재시작하는 현상 수정
=> fix: 오버레이컨트롤러 healthcheck 실패 버그 수정

apps/web-kkshow/pages/mypage/orders/index.tsx, apps/web-kkshow/pages/payment/success.tsx, libs/components-shared/src/lib/LoginForm.tsx, libs/components-web-kkshow/src/lib/payment/DeliveryAddress.tsx, libs/nest-modules-customer/src/lib/customer.controller.ts, libs/nest-modules-customer/src/lib/customer.service.ts, libs/prisma-orm/prisma/migrations/20220418010639_ecommerce/migration.sql, libs/prisma-orm/prisma/schema.prisma, libs/prisma-orm/prisma/seedData/customer.ts
- 크크쇼 소비자 아바타 변경 가능하도록 수정
- 결제페이지 토스페이먼츠 결제승인요청에 대한 에러핸들러 추가
- 결제페이지 우편번호 옆 주소검색 버튼이 튀어나가 레이아웃 틀어진거 수정
=> [크크쇼] 오류수정 : 소비자 아바타 변경불가 외

apps/api/src/settings/appSetting.ts, libs/nest-core/src/lib/constants/csrf-free-routes.ts, libs/nest-core/src/lib/index.ts, libs/nest-core/src/lib/settings/csrf.config.ts
=> feat: GET,HEAD,OPTIONS 요청에 대해 csrf 방어 제거

apps/overlay-controller/src/app/app.controller.ts, apps/overlay-controller/src/app/auth.contoller.ts, apps/overlay-controller/src/lib/login.js
=> feat: 오버레이 컨트롤러 어드민 가드 적용

apps/overlay-controller/src/lib/admin.js, apps/overlay-controller/src/lib/login.js, apps/overlay-controller/src/views/login.hbs
=> fix: 오버레이 컨트롤러 로그인 에러 수정

libs/components-web-kkshow/src/lib/AgreementDialog.tsx, libs/components-web-kkshow/src/lib/mypage/info/UserInfo.tsx
=> feat: 회원정보수정 - 약관 동의 기능 추가

libs/components-web-kkshow/src/lib/goods/GoodsInquiryFormDialog.tsx, libs/components-web-kkshow/src/lib/goods/GoodsViewInquiries.tsx, libs/components-web-kkshow/src/lib/mypage/orderList/CustomerOrderItemActionButtons.tsx
- 크크쇼>마이페이지>주문/배송내역 ’문의하기’ 클릭 시 아무 작동을 하지 않음
- 상품 상세페이지에는 상품에 대한 문의 남길 수 있는 다이얼로그 있음
=> fix: 크크쇼 주문내역에서 문의하기 버튼 미동작

libs/components-web-kkshow/src/lib/GoodsDisplay.tsx, libs/components-web-kkshow/src/lib/goods/GoodsViewMeta.tsx, libs/components-web-kkshow/src/lib/payment/OrderItemInfo.tsx, libs/nest-modules-kkshow-search/src/kkshow-search/kkshow-search.service.ts
=> fix: 0.8.1 버그수정

apps/web-kkshow/pages/_app.tsx, apps/web-kkshow/pages/mypage/info.tsx, libs/components-admin/src/lib/AdminLoginForm.tsx, libs/components-admin/src/lib/AdminSignUp.tsx, libs/components-seller/src/lib/LiveShoppingRegistManagerContacts.tsx, libs/components-seller/src/lib/goods-regist/GoodsRegistCommonInfo.tsx, libs/components-shared/src/lib/LoginForm.tsx, libs/components-shared/src/lib/MypageErrorBoundary.tsx, libs/components-shared/src/lib/MypageLayout.tsx, libs/components-shared/src/lib/PasswordCheckForm.tsx, libs/components-shared/src/lib/ResetPasswordForm.tsx, libs/components-shared/src/lib/signup/SignupAgreeTerms.tsx, libs/components-shared/src/lib/signup/SignupForm.tsx, libs/components-shared/src/lib/signup/SignupStart.tsx, libs/components-web-kkshow/src/lib/AgreementDialog.tsx, libs/components-web-kkshow/src/lib/ErrorBoundary.tsx, libs/components-web-kkshow/src/lib/mypage/CustomerStatusSection.tsx, libs/components-web-kkshow/src/lib/mypage/info/CustomerNicknameChangeDialog.tsx, libs/components-web-kkshow/src/lib/mypage/info/UserInfo.tsx, libs/components-web-kkshow/src/lib/payment/BuyerInfo.tsx, libs/nest-modules-broadcaster/src/broadcaster/broadcaster.service.ts, libs/nest-modules-customer/src/lib/customer.service.ts, libs/nest-modules-policy/src/policy/policy.controller.ts, libs/nest-modules-seller/src/seller/seller.service.ts, libs/prisma-orm/prisma/seedData/dummyData.ts, libs/prisma-orm/prisma/seedData/terms.ts
- 상품공통정보 시드 변경 (상품공통정보기본값 개선사항은 DB 모델링 작업이 포함되므로 향후 정식 스프린트에서 진행)
- 소비자 마이페이지 정보 이메일 -> 닉네임
- 소비자 정보 이메일 -> 닉네임으로 수정 및 닉네임 설정 추가
- 크크쇼 클라이언트 에러페이지 추가( 테스트: Error를 만드는 테스트용 페이지 구성 )
- 방송인/판매자 마이페이지 에러페이지 추가( 테스트: Mypage 아래에 Error를 만드는 테스트용 페이지 구성 )
- 방송인/판매자/소비자 회원가입시 이용약관 동의절차 추가
- 로그인화면, 소비자 마이페이지 정보변경탭 간단한 디자인 개선
=> improve: 0.8.1 개선사항

apps/overlay-controller/src/views/index.hbs, apps/overlay/src/app/app.controller.ts, apps/overlay/src/app/app.gateway.ts, apps/overlay/src/app/app.message.gateway.ts, apps/overlay/src/app/app.screen.gateway.ts, apps/overlay/src/lib/animation.js, apps/overlay/src/lib/nslOverlayClient.js, apps/overlay/src/lib/overlayClient.js, apps/overlay/src/views/client.hbs, libs/nest-modules-overlay-controller/src/overlay-controller/overlay-controller.service.ts, libs/nest-modules-overlay/src/overlay/overlay.service.ts
=> chore: 코드 주석 설명 추가

apps/web-kkshow/pages/privacy.tsx, apps/web-kkshow/pages/termsOfService.tsx, libs/components-constants/src/lib/footerLinks.ts, libs/components-shared/src/lib/PolicyWrapper.tsx
- 크크쇼(쇼핑) 페이지 하단 푸터
이용약관, 개인정보처리방침 페이지 노션 공공페이지 링크 => 크크쇼 내부페이지로 변경
- 크크쇼 하단 푸터 사업장소재지 => 이사한 주소로 변경
=> [크크쇼] 소비자 이용약관, 개인정보처리방침 페이지

libs/nest-modules-admin/src/admin/admin.service.ts, libs/nest-modules-liveshopping/src/live-shopping/live-shopping.service.ts, libs/nest-modules-product-promotion/src/lib/product-promotion.service.ts
장바구니에 담았던 상품의 상품홍보가 삭제되거나 끝난 경우, 방송인을 후원할 수 없으므로, 장바구니 등록시 작성했던 support 정보가 사라져야 하지만 그대로 표시되는 버그.
상품홍보가 삭제된 경우 (관리자가 productPromotion을 삭제한 경우)
- CartItemSupport 에서 해당 support를 삭제해야 한다.
(만약 해당 상품의 라이브쇼핑이 존재한다면 삭제하지 않는다)
- CartItem(카트상품) channel 올바르게 변경
라이브쇼핑이 삭제되거나 취소된 경우
- CartItemSupport 에서 해당 support를 삭제해야 한다.
(만약 해당 상품의 상품홍보가 존재한다면 삭제하지 않는다)
- CartItem(카트상품) channel 올바르게 변경
시나리오:
1. 라이브쇼핑 또는 상품홍보 등록된 상품을 장바구니에 담는다
2. 장바구니에 담은 이후, 관리자가 라이브쇼핑을 취소상태로 변경하거나, 삭제하거나, 상품홍보를 삭제한다
3. 장바구니에 다시 입장하여 확인한다.
=> [관리자/판매자/방송인] 버그: 상품홍보/라이브쇼핑 삭제시 장바구니Item의 support 삭제

libs/components-admin/src/lib/mileage-setting/AdminOrderMileageSetting.tsx, libs/hooks/src/lib/mutation/useOrderPurchaseConfirmMutation.tsx
- 구매확정 이후 소비자 마일리지 업데이트
- 관리자 - 마일리지 기능 => 마일리지 적립기능으로 명시
=> fix : 버그수정 (구매확정 이후 소비자 마일리지 업데이트)

apps/admin/pages/live-shopping/[liveShoppingId].tsx, libs/components-admin/src/lib/AdminLiveShoppingList.tsx, libs/hooks/src/lib/mutation/useGoodConfirmationMutation.tsx, libs/hooks/src/lib/mutation/useGoodRejectionMutation.tsx
- 상품 검수 이후 라이브쇼핑에 포함된 상품 검수상태 초기화안되는 버그
- 라이브쇼핑에 등록된 상품 검수 거절시 처리 추가
=> fix: 테스트 버그 수정

apps/admin/pages/order/list/[orderId].tsx
- 토스페이먼츠로부터 결제정보를 받아올 수 없는 경우 모든 주문정보를 확인할 수 없는 버그 수정
=> fix(admin): 주문상세 확인못하는 현상 수정

libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
=> feat: 크크쇼:상품옵션 - 특가의 경우 특가 표시추가

libs/components-web-kkshow/src/lib/goods/GoodsViewMeta.tsx
라이브쇼핑 특가 일감 피드백 반영 - 크크쇼 상품 상세페이지 판매가 아래 라이브특가 표시 추가
=> feat : 크크쇼 상품상세페이지 판매가 아래 특가 추가

libs/nest-modules-order/src/lib/order.service.ts
주문상세조회시 복호화처리가 없었음
가상계좌결제인 경우 올바르게 복호화하여 은행명과 가상계좌를 표시하도록 수정함
=> fix(kkshow) : 가상계좌로 결제한 주문 상세페이지에서 가상계좌번호 올바르게 표시

apps/web-kkshow/pages/payment/fail.tsx, apps/web-kkshow/pages/payment/success.tsx, libs/hooks/src/lib/mutation/useOrderMutation.tsx, libs/hooks/src/lib/mutation/usePaymentMutation.tsx, libs/nest-modules-order/src/lib/order.service.ts, libs/nest-modules-payment/src/lib/payment-exception.filter.ts, libs/nest-modules-payment/src/lib/payment.controller.ts, libs/nest-modules-payment/src/lib/payment.service.ts, libs/shared-types/src/lib/res-types/paymentsRes.res.ts, libs/utils/src/lib/tossPaymentsApi.ts
'결제는 진행되었으나 주문은 생성되지 않는 버그'의 원인을 정확하게 찾을 수 없었음.
근본적인 버그 수정은 못하고 리팩토링만 진행
- 오류발생 가능성이 있는 부분 일부 수정 (주문아이템 생성시 support 가 존재하는 경우 optional 인 값에 옵셔널체이닝 적용, payment값이 존재하지 않는경우 주문상태 처리 등)
- 기존 크크쇼에서는 프론트에서 결제승인요청 이후 응답을 받고, 별도로 주문생성 요청을 보냄  => 결제승인요청 라우터 내에서 주문생성까지 처리하도록 수정. 프론트는 응답으로 받은 에러메시지만 출력함
- 토스페이먼츠 결제는 완료되었으나, 과정 중 생긴 오류로 인해 주문이 생성되지 않는경우 완료된 토스페이먼츠 결제를 취소처리함
- 주문실패 페이지에 '주문서로 돌아가기' 버튼 추가
결제-> 주문생성 과정을 3단계로 구분함
1. 토스페이먼츠 결제승인요청
2. 크크쇼 OrderPayment 생성
3. 크크쇼 Order 생성
단계 2,3에서 에러 발생시 단계 1에서 승인된 토스페이먼츠 결제내역을 취소하도록 에러핸들링 적용
모든 단계에서 에러가 발생하지 않아야 정상적으로 크크쇼 주문데이터가 생성됨
1. 단계 1에서 오류 발생  => 토스페이먼츠 결제 중 오류. 토스페이먼츠에서 보낸 에러메시지를 프론트에 출력
2. 단계 2에서 오류 발생  => 토스페이먼츠 결제승인됨. 크크쇼 OrderPayment 데이터 생성중 오류발생. 승인된 토스페이먼츠 결제 취소처리하고 '결제데이터 생성 중 오류 발생' 문구를 프론트에 출력
3. 단계 3에서 오류 발생 => 토스페이먼츠 결제승인됨. 크크쇼 …
=> refactor(api, kkshow) : 결제 및 주문생성 관련 코드 수정

libs/components-web-kkshow/src/lib/payment/DeliveryAddressDialog.tsx, libs/components-web-kkshow/src/lib/payment/DeliveryAddressList.tsx, libs/components-web-kkshow/src/lib/payment/OrderPaymentForm.tsx, libs/prisma-orm/prisma/seed.ts
fix: 배송지 자동 지정 테스트 피드백 수정
improve: 결제페이지 배송지 주소찾기시 주소 선택 이후 상세주소란으로 자동 포커스
chore: 기본 배송지 시드 값 수정
=> fix: Hwasurr address automation fix

apps/web-kkshow/pages/bc/[broadcasterId].tsx, apps/web-kkshow/pages/index.tsx, apps/web-kkshow/pages/shopping/index.tsx, libs/components-web-kkshow/src/lib/EventPopup.tsx, libs/prisma-orm/prisma/migrations/20220906024825_/migration.sql, libs/prisma-orm/prisma/schema.prisma
- 추석 배송 팝업 추가
- 외부상품 타입 수정 (외부상품 링크가 매우 긴 경우 오류가 나서 변경함)
=> feat : 추석 배송 팝업 추가, fix : 외부상품 스키마 타입 수정

libs/components-web-kkshow/src/lib/EventPopup.tsx
=> fix : 9월 13일부터 추석배송 팝업 안뜨도록 수정

apps/web-kkshow/pages/_app.tsx, apps/web-kkshow/pages/payment/receipt.tsx, libs/components-web-kkshow/src/lib/cart/CartActions.tsx, libs/components-web-kkshow/src/lib/cart/CartTable.tsx, libs/components-web-kkshow/src/lib/goods/GoodsViewMeta.tsx, libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx, libs/components-web-kkshow/src/lib/mypage/orderList/OrderCancelDialog.tsx, libs/components-web-kkshow/src/lib/payment/OrderPaymentForm.tsx, libs/utils-frontend/src/index.ts, libs/utils-frontend/src/lib/ga4DataLayer.ts
전자상거래 이벤트 데이터 전송 위해
dataLayer에 관련 데이터 추가하는 코드 삽입
=> feat : 크크쇼 GA4 전자상거래 태그 설정

apps/overlay-controller/src/assets/layout.css, apps/overlay-controller/src/lib/admin.js, apps/overlay-controller/src/views/index.hbs, apps/overlay/src/assets/layout.css, apps/overlay/src/lib/overlayClient.js, apps/overlay/src/views/client.hbs, libs/components-admin/src/lib/live-shopping/AdminLiveShoppingSalesGuideImageUploadDialog.tsx, libs/components-admin/src/lib/live-shopping/AdminLiveShoppingUpdateForm.tsx, libs/nest-modules-overlay/src/overlay/overlay.screen.gateway.ts
* 판매가이드 이미지 : 방송인이 제품 설명 시 참고할 이미지, 오버레이 우측 상단에 표시한다
- 관리자 > 라이브쇼핑 > 판매가이드 이미지 추가
- 오버레이 컨트롤러 > 판매가이드 띄우기, 숨기기
- 오버레이 > 판매가이드 표시
=> feat : [관리자] 판매가이드 이미지 추가, [오버레이] 판매가이드 표시

apps/overlay-controller/src/lib/admin.js, apps/overlay/src/lib/overlayClient.js, package.json, yarn.lock
@aws-sdk/util-endpoints 패키지 설치했음에도 
해당 모듈을 찾을 수 없다는 오류가 뜸
=> https://github.com/aws/aws-sdk-js-v3/issues/4060 
해당 모듈 버전 올림
=> chore : @aws-sdk/util-endpoints

apps/overlay-controller/src/lib/admin.js, apps/overlay/src/lib/overlayClient.js, package.json, yarn.lock
@aws-sdk/util-endpoints v3.192.0 오류가 수정된 새로 배포된 버전(3.193.0)으로 업그레이드
=> chore : dependency @aws-sdk/util-endpoints 버전 업그레이드

libs/components-seller/src/lib/ShippingOptionIntervalApply.tsx, libs/components-seller/src/lib/ShippingOptionRepeatApply.tsx, libs/components-web-bc/src/lib/OverlayUrlCard.tsx, libs/components-web-bc/src/lib/PromotionPageUrlCard.tsx, libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
[크크쇼]
- 상품1 상세페이지에서 선택한 옵션이, 상품2 상세페이지에도 표시되는 문제 수정
- 상품1 상세페이지에서 선택한 후원방송인이, (해당 후원방송인이 상품2도 홍보중인 경우)상품2 상세페이지에서도 후원방송인으로 유지되는 문제 수정
[방송인]
마이페이지 홈 상품홍보페이지 url 복사 컴포넌트 표시되지 않는데 원인을 몰라 문구만 수정
=> fix : 버그수정

apps/web-broadcaster-center/pages/mypage/index.tsx
=> chore : 변수명 수정

libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
- 선물하기 버튼 눈에 띄게 하기 위해 다른버튼과 동일한 크기로 키움
- 다른 버튼과 구별되는 핑크색 사용
=> refactor : 선물하기 버튼 크기 & 색 변경

libs/nest-modules-product-promotion/src/lib/product-promotion.service.ts
- 상품홍보 삭제시, 연결된 장바구니 상품 삭제하는 prisma 코드에 오류가 있었음
=> fix : [관리자] 상품홍보페이지 상품 삭제시 오류 수정

libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
- 후원방송인 정보 중 아바타 중앙정렬
- 후원방송인 정보 중 아이디 중앙정렬
=> kkshow-후원방송인 정보 정렬

apps/api/Dockerfile, apps/overlay-controller/Dockerfile
=> chore: 20230422 ECR 이미지 삭제로 인한 재배포 트리거 커밋
