- apps/api/src/main.ts
- apps/api/src/settings/appSetting.ts
- libs/hooks/src/axios.ts
현재 코드에서는 host명이 고정되어 있어 테스트 환경에서 (localhost) 통신에 대한 테스트를 올바르게 진행할 수 없다.
환경변수 추가 `API_HOST`
- 테스트 환경
> [Infra Update] test(dev) 환경의 서버간 통신을 위한 환경변수 처리

- libs/components/src/lib/ExportManyDialog.tsx
- libs/components/src/lib/GoodsExposeSwitch.tsx
- libs/components/src/lib/OrderList.tsx
- libs/components/src/lib/SellerGoodsList.tsx
스타일 수정사항
- dataGrid 내에서 사용된 Switch 레이아웃 깨진거 수정
- 상품, 주문 테이블 컬럼 구분선 추가
기능 수정사항
- 상품 상세보기 화면에서 상품노출 변경시 상품목록에서도 해당 변경사항 반영하도록 수정
- 합포장 출고처리 성공 후 출고처리 모달창 닫기
> 1차스프린트 내부 시연회 후 피드백 수정사항 2

- libs/components/src/lib/BusinessRegistrationDialog.tsx
- libs/components/src/lib/BusinessRegistrationForm.tsx
- libs/components/src/lib/LoginForm.tsx
- libs/components/src/lib/SettlementAccountDialog.tsx
- 사업자 등록증 이메일 입력시 에러 핸들링을 react-hook-form으로 통일
- error의 status code의 조회방법 수정
- ~사업자 등록증 주소 입력 구현 도중, 모달창의 크기, 상세 주소 입력등 필요 수정이 많을 것으로 보고 추 후로 미룸~
> [Fix] 시연회 수정 필요사항 추가

- libs/components/src/lib/GoodsDetailOptionsInfo.tsx
- libs/components/src/lib/GoodsRegistDataOptions.tsx
- libs/components/src/lib/SellerGoodsList.tsx
- libs/components/src/lib/StockInfoButton.tsx
프론트단에서 재고 부분이 보여지는 코드만 주석처리함 (서버, db관련 코드는 수정하지 않음)
상품 목록 페이지 /mypage/goods
-  '재고/가용', '재고판매' 컬럼 주석처리
상품 상세 페이지(판매자, 관리자 페이지 공통 컴포넌트 사용) /mypage/goods/:id, admin/goods/:id
- 옵션 표에서 재고, 불량재고, 가용재고 컬럼 주석처리
상품 등록 페이지 /mypage/goods/regist
- 판매옵션에서 '재고'입력칸 주석처리 (원래 값을 입력받지 않아도 db에는 재고 0으로 저장됨)
상품 등록 페이지
상품 목록 페이지
상품 상세 페이지(판매자, 관리자 공통)
> [상품 옵션] 재고 기능 임시 제거

- libs/components/src/lib/BusinessRegistrationDialog.tsx
- libs/components/src/lib/BusinessRegistrationForm.tsx
- libs/components/src/lib/BusinessRegistrationMailOrderNumerSection.tsx
- libs/components/src/lib/admin/AdminBusinessRegistrationList.tsx
- libs/hooks/src/lib/s3.tsx
- libs/nest-modules/src/lib/seller/seller-settlement.service.ts
- libs/prisma-orm/prisma/migrations/20211007021538_/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/shared-types/src/lib/dto/businessRegistration.dto.ts
- 필수로 등록
- 입력 제한은 없이, 10자 이상의 길이제한만 추가
- 선택으로 등록
1. fileName → businessRegistrationImageName 로 변경
2. mailOrderSalesImageName : 통신판매업신고증의 저장된 이미지이름
3. mailOrderSalesNumber : 통신판매업신고번호
- 전체 주소를 확인하기 위해 여백 제공
- fileName → businessRegistrationImageName 수정
- 신고증을 업로드하지 않은경우, 버튼 클릭 불가능
> [기능 추가] 사업자 등록정보 등록시 통신판매업 신고 정보 등록 구현

- libs/components/src/lib/ExportDetailItems.tsx
- libs/components/src/lib/OrderDetailDeliveryInfo.tsx
- libs/firstmall-db/src/__tests__/exportSample.ts
- libs/firstmall-db/src/__tests__/orderDetailSample.ts
- libs/firstmall-db/src/lib/fm-exports/fm-exports.service.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.spec.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts
- libs/shared-types/src/lib/res-types/fmExport.res.ts
- libs/utils/.babelrc
- libs/utils/.eslintrc.json
- libs/utils/README.md
- libs/utils/jest.config.js
- libs/utils/src/index.ts
- libs/utils/src/lib/fmOrderMemoParser.ts
- libs/utils/src/lib/parseFmOrderMemo.spec.ts
- libs/utils/src/lib/utils.spec.ts
- libs/utils/src/lib/utils.ts
- libs/utils/tsconfig.json
- libs/utils/tsconfig.lib.json
- libs/utils/tsconfig.spec.json
- nx.json
- tsconfig.base.json
- workspace.json
1. nx 라이브러리 생성 = utils
1. 목적: 유틸함수 모음 (이 일감에서는, 배송메모 파싱함수)
2. 파싱 함수 작성
3. API orders service 배송 메모 파서 적용
4. Web 주문상세보기 배송메모 필드 추가
5. [추가 진행 작업] 출고 주문정보 주문별 주문번호 링크 추가
> [마이페이지 - 주문상세보기] 배송메모 추가

- apps/web/pages/mypage/orders/[orderId].tsx
- libs/components/src/lib/ExportDialog.tsx
- libs/components/src/lib/ExportManyDialog.tsx
- libs/components/src/lib/ExportOrderOptionList.tsx
- libs/components/src/lib/LoginForm.tsx
- libs/components/src/lib/OrderDetailExportInfo.tsx
- libs/components/src/lib/OrderDetailOptionList.tsx
- libs/components/src/lib/OrderDetailSummary.tsx
- libs/components/src/lib/OrderList.tsx
- libs/firstmall-db/src/__tests__/orderDetailSample.ts
- libs/firstmall-db/src/__tests__/ordersSample.ts
- libs/firstmall-db/src/lib/fm-exports/fm-exports.service.spec.ts
- libs/firstmall-db/src/lib/fm-exports/fm-exports.service.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.controller.spec.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.controller.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.spec.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts
- libs/hooks/src/lib/useOrderExportableCheck.tsx
- libs/prisma-orm/prisma/seed.ts
- libs/shared-types/src/lib/constants/fmOrderShippingTypes.ts
- libs/shared-types/src/lib/dto/exportOrder.dto.ts
- libs/shared-types/src/lib/res-types/fmOrder.res.ts
- libs/stores/src/lib/fmExportStore.tsx
- libs/utils/src/lib/fmOrderMemoParser.ts
- libs/utils/src/lib/parseFmOrderMemo.spec.ts
입점형태이므로 구매자가 주문할 때
판매자A 의 ㄱ상품, 판매자B의 ㄴ상품과 같이 여러 판매자의 상품을 주문할 수 있다.
판매자A의 마이페이지 주문목록/주문상세보기 에서는 어떻게 보여져야 하는가?
→ 주문에서 판매자A의 상품인 ㄱ상품의 정보만 보여주도록 합의
⇒ 이에 따른 처리 필요
- 주문(상품,옵션) 금액
- 주문상품,옵션 보여지지 않도록
- 주문 목록의 결제금액을 settleprice 를 참조하지 않고 다음과 같이 수정
현재 주문한 판매자의 상품/상품옵션별 금액의 합 + 상품의 배송정책 배송비
주문 중, 자신의 상품정보만 확인할 수 있도록 처리
- 주문 목록
- 주문 상세 보기
- 출고 상세 보기
- ~~출고 주문 정보~~
- 출고하기
- "주문상태" 관련
1. 하나의 주문에 여러 판매자가 관여하므로, 판매자A는 "출고완료" 상태이지만 판매자 B는 "상품준비" 상태일 수 있음. 하지만 주문의 "상태" 는 하나이므로 판매자A와 판매자B에게 보여지는 주문 상태는 "상품준비" 가 될 것.
⇒ 판매자 A는 왜 주문 상태가 변하지 않는가? 혼란을 느낄 수 있음.
2. 출고처리시 출고완료로 주문 상태를 변경해 버림.
예를 들면, 판매자B는 아직 "상품준비" 상태일 때, 판매자 A가 출고를 진행하여 "출고완료"로 상태를 변경하면, 주문의 상태는 "출고완료"가 되어버림.
⇒ 판매자 B는 주문상태가 왜 이렇지? 혼란을 느낄 수 있음.
해결책
1. "주문" 의 상태를 주문의 "step" 필드를 참조하지 않고, 주문에 포함된 내 상품과 내 상품 옵션의 정보를 토대로 유추한다
> [판매자 마이페이지 - 주문목록/주문상세보기] 주문에 다른 판매자의 상품이 포함된 경우의 처리

- apps/admin/pages/live-shopping/[liveShoppingId].tsx
- libs/components/src/lib/admin/AdminLiveShoppingList.tsx
- 라이브 쇼핑 목록에서 행 클릭시 개별 라이브 쇼핑 페이지 이동
- 요청사항 확인칸 추가
- sellerShop 없을 때, 에러 해결
> [버그수정] 관리자 페이지 - 라이브 쇼핑 관리

- apps/web/pages/mypage/goods/[goodsId].tsx
- libs/components/src/lib/GoodsDetailActions.tsx
- libs/components/src/lib/GoodsDetailTitle.tsx
- libs/components/src/lib/GoodsEditForm.tsx
- libs/components/src/lib/GoodsExposeSwitch.tsx
- libs/components/src/lib/SellerGoodsList.tsx
- libs/components/src/lib/ShopInfoShippingGroup.tsx
- libs/hooks/src/index.ts
- libs/hooks/src/lib/useGoodsOnLive.tsx
- libs/nest-modules/src/lib/goods/goods.service.spec.ts
- libs/nest-modules/src/lib/goods/goods.service.ts
- libs/shared-types/src/lib/res-types/goodsById.res.ts
- libs/shared-types/src/lib/res-types/goodsList.res.ts
- 특정 상품이 라이브쇼핑 진행중인 경우 상품정보 수정 못하도록 처리(라이브쇼핑이 등록된 상품 삭제와 동일한 기준 사용 - 라이브쇼핑이 취소됨/진행완료 인 경우에는 수정 가능. 이 외에는 불가)
- 노출버튼 disable
- 수정버튼(수정페이지로 이동 링크) 숨김처리
이유
-  판매자가 실수로 라이브쇼핑중인 상품을 숨김처리 하지 않도록 하기 위함이다. 라이브쇼핑 진행중인 상품은 검수된 상품이다. 검수된 상품 노출여부 변경시 검수과정 없이 퍼스트몰 상품의 노출여부도 변경된다.
- 라이브쇼핑 등록된 상품의 상품명을 변경하는 경우, '내 라이브쇼핑 관리' 페이지에 표시되는 상품명도 변경된다. 하지만 실제 크크마켓에 표시되는 상품명은 퍼스트몰에서 관리자가 수정하기 전에는 변경되지 않는다. 판매자가 상품명이 즉각적으로 변경되었다고 오해하는 일을 방지하고자 함. 
기타 수정사항 
- 배송비정책 목록 컨테이너 스타일 수정
> [기능 수정] 상품수정 기능 - 라이브쇼핑이 진행중인경우 불가능하도록 처리

- apps/web/pages/mypage/orders/[orderId].tsx
- apps/web/pages/mypage/settlement/index.tsx
- aws-cdk/lib/dev/app-stack.ts
- aws-cdk/lib/env-agnostic/domain-stack.ts
- libs/components/src/lib/ExportBundleDialog.tsx
- libs/components/src/lib/ExportDialog.tsx
- libs/components/src/lib/OrderDetailExportInfo.tsx
- libs/components/src/lib/settlement/AdminSettlementDoneList.tsx
- libs/components/src/lib/settlement/SettlementInfoDialog.tsx
- libs/components/src/lib/settlement/SettlementList.tsx
- libs/components/src/lib/settlement/SettlementTargetList.tsx
- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.spec.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts
- libs/hooks/src/lib/useOrderExportableCheck.tsx
- libs/prisma-orm/prisma/migrations/20211029050313_version2/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/utils/src/lib/calcPgCommission.ts
- tools/ignore-admin-vercel-build.sh
(ex. 주문에 내 상품이 아닌 상품의 상태가 출고완료고, 내 상품이 결제확인인 경우, 주문목록과 주문상세보기에서 결제확인으로 표시되나, 결제확인으로 필터링(검색)했을 때 뜨지않고 출고완료로 필터링(검색)했을때 뜸)    
⇒ 주문목록의 '주문상태' 필터링을 내상품의 옵션의 상태와 주문 상태를 함께 고려한 값인 realStep을 계산한 뒤로 미루는 방식으로 변경하여 해결
- 하나만 남아서 출고하는 경우에는 합포장 출고처리가 불가능하도록 막야아함.    
→ 조사결과, 주문의 step이 15, 25, 35, 40, 45, 50, 55, 60, 65, 70, 75, 85, 95, 99 가 아닌 값을 가지는 주문이 존재했다. 해당 오류가 발생한 이유도 step이 0으로 처리된 주문이 포함되어 조회되었기 때문이었다.
→ 퍼스트몰상에서 step이 범위를 벗어나는 주문에 대해서 어떻게 처리하나 확인했더니, 아예 조회가 불가능했다. 따라서 step 범위를 벗어나지 않는 주문만 조회하도록 처리함.
> 개발자간 통합테스트 이후 수정사항

- apps/admin/pages/live-shopping/[liveShoppingId].tsx
- libs/components/src/lib/BroadcasterChannelButton.tsx
- libs/components/src/lib/LiveShoppingDatePicker.tsx
- libs/components/src/lib/LiveShoppingList.tsx
- libs/components/src/lib/OrderReturnStatusDialog.tsx
- libs/hooks/src/lib/mutation/useCreateLiveShopping.tsx
- libs/hooks/src/lib/mutation/useDeleteLiveShoppingMutation.tsx
- libs/hooks/src/lib/mutation/useUpdateLiveShoppingManageMutation.tsx
- libs/nest-modules/src/lib/admin/admin.controller.ts
- libs/nest-modules/src/lib/admin/admin.service.ts
> [버그수정] 라이브 쇼핑 관리 페이지

- libs/components/src/lib/GoodsEditForm.tsx
- libs/components/src/lib/GoodsRegistCommonInfo.tsx
- libs/components/src/lib/GoodsRegistDataBasic.tsx
- libs/components/src/lib/GoodsRegistDataOptions.tsx
- libs/components/src/lib/GoodsRegistDataSales.tsx
- libs/components/src/lib/GoodsRegistDescription.tsx
- libs/components/src/lib/GoodsRegistExtraInfo.tsx
- libs/components/src/lib/GoodsRegistForm.tsx
- libs/components/src/lib/GoodsRegistMemo.tsx
- libs/components/src/lib/GoodsRegistPictures.tsx
- libs/components/src/lib/GoodsRegistShippingPolicy.tsx
- libs/components/src/lib/SectionWithTitle.tsx
로버트님 피드백 반영
- 옵션명 추가할 수 있도록 수정(최대 5개 - 퍼스트몰 옵션명 5개 제한)
- (옵션명 = `<select>` 컴포넌트 1개, 옵션값 = `<select>`안에 렌더링되는 `<option>` 과 유사)
- 옵션값을 `,`로 구분하여 입력할 수 있는 형태로 수정
- 옵션값 옆에 i 버튼으로 설명 추가함
- 옵션값을 콤마로 구분하여 입력하는 형태는 쇼핑몰 옵션 입력시 일반적인 형태로 보임 - 퍼스트몰, 네이버 스마트스토어 옵션입력부분 참고하였음)
- 옵션명, 옵션값 placeholder 추가
- 상품등록, 수정페이지 섹션 스타일 수정(테두리 추가하여 각 영역별 구분을 명확하게 함
---
1. 옵션명, 옵션값 입력 후 버튼을 누르면
2. 옵션명:옵션값 형태의 옵션이 생성. 여기서 가격, 노출정보 입력하는 형태
> [2차 스프린트 피드백 반영] 판매자페이지 상품 옵션 입력 폼 수정

- libs/components/src/constants/navigation.ts
- libs/components/src/lib/GoodsRegistCommonInfo.tsx
- libs/components/src/lib/GoodsRegistDescription.tsx
- libs/components/src/lib/GoodsRegistForm.tsx
- libs/components/src/lib/GoodsRegistPictures.tsx
- libs/components/src/lib/Navbar.tsx
- libs/components/src/lib/ShippingOptionFixedApply.tsx
- libs/components/src/lib/ShippingOptionIntervalApply.tsx
- libs/components/src/lib/ShippingOptionRepeatApply.tsx
- libs/components/src/lib/ShippingPolicyBasicInfo.tsx
- libs/shared-types/src/lib/constants/shippingTypes.ts
- libs/stores/src/lib/shippingGroupItemStore.tsx
- 기본 배송비, 추가 배송비 모두 무료.
- 기본 배송비만 무료. (추가 배송비는 부과됨)
- 추가 배송비만 무료. (기본 배송비는 부과됨)
- 기본 배송비, 추가 배송비 모두 부과
> [2차 스프린트 피드백 반영] 상품 등록 관련 사용성 개선 피드백 반영

- apps/admin/pages/live-shopping/[liveShoppingId].tsx
- libs/components/src/lib/ChakraAutoComplete.tsx
- libs/components/src/lib/LiveShoppingList.tsx
- libs/components/src/lib/LiveShoppingRegistForm.tsx
- libs/components/src/lib/LiveShoppingRegistManagerContacts.tsx
- libs/components/src/lib/LiveShoppingRegistRequestField.tsx
- libs/nest-modules/src/lib/live-shopping/live-shopping.service.ts
- libs/prisma-orm/prisma/migrations/20211206063831_/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/shared-types/src/lib/dto/liveShopping.dto.ts
- libs/shared-types/src/lib/front-type/liveShoppingInputType.ts
- libs/utils/src/lib/checkOrderDuringLiveShopping.spec.ts
- libs/utils/src/lib/getHostUrl.ts
- 희망진행기간
- 희망판매수수료
- 라이브쇼핑 등록시
- 라이브쇼핑 조회시
- 관리자페이지
> [판매자센터] 라이브쇼핑 등록시 입력정보 추가

- libs/nest-modules/src/lib/admin/admin.controller.ts
- libs/nest-modules/src/lib/auth/auth.service.ts
로그인 관련 로직을 구현하였으나 로컬 환경에서는 로그인 유지 상태를 구현할 수 없어서 테스트는 불가. 
배포 후, 확인 필요.
> [Add] 관리자 -> 방송인 / 판매자 로그인 유지 삭제

- libs/components-admin/src/lib/AdminPageLayout.tsx
- libs/components-admin/src/lib/AdminSidebar.tsx
사이드바와 상단 네비바, 메인화면을 고정해둔 채 메인화면 overflow 시 스크롤이 생기도록 구성했습니다
상단 네비바도 화면에 고정되어 있으면 좋겠다 싶어서요
내일 확인해 보시고 피드백 부탁드립니다.
판매자센터, 방송인센터, 크크쇼 페이지에서는 태블릿,모바일 화면에서는 기본으로 사이드바가 닫혀있는 형태이면서, 메인화면의 크기를 줄이지 않고 모달 + 오버레이 형태로 뜨는 식으로 구현해야 할 것 같습니다. (chakra-ui 에서 제공하는 Drawer 와 비슷하게)
> fix: nav 디자인 및 admin 레이아웃 수정

- libs/components-web-bc/src/lib/main/BroadcasterMainHero.tsx
썸네일 자동재생 오른쪽으로
자리 변경되는 썸네일이 다른 썸네일 아래로 지나가도록 수정해봤습니다(last index일 때 zindex 를 낮게)
이러면 어떤가요??
> fix: 방송인 메인페이지 피드백 - 캐러셀 자동 넘김시 이미지가 맨 뒤로 이동

- apps/web-broadcaster-center/pages/signup.tsx
- libs/components-shared/src/lib/MypageBreadCrumb.tsx
버그 제보 : 방송인센터 소셜 회원가입시 판매자 센터가 가입이 됩니다. 리다이렉트도 판매자 센터
원인 : 방송인센터와 판매자센터에서 각자 사용되던 로그인 컴포넌트를 공용컴포넌트로 만들면서 appType을 props로 넘겨줌
복사 붙여넣기 하다가 방송인센터 로그인 컴포넌트에도 appType = 'seller'로 잘못 넘김
수정사항 : 방송인센터 로그인 컴포넌트  appType = 'broadcaster'로 수정함
> fix : 방송인센터 로그인 컴포넌트 appType 수정

- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts
- 라이브 쇼핑 매출 결제취소액 제외 및 쿼리 오류 수정
> fix: 라이브 쇼핑 매출 결제취소액 제외 및 쿼리 오류 수정

- libs/prisma-orm/prisma/migrations/20220207074141_/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/prisma-orm/prisma/seed.ts
1. BroadcasterPromotionPage 방송인 상품홍보 페이지
- id : int
- url : string?  @unique
- broadcaster : Broadcaster
- broadcasterId : int
- productPromotions : ProductPromotion[]
2. ProductPromotion 상품 홍보 아이템
- id : int
- fmGoodsSeq : int?
- goods : Goods
- goodsId: int
- broadcasterPromotionPage : BroadcasterPromotionPage
- broadcasterPromotionPageId : int
- broadcasterCommissionRate : Decimal          default(5.00)     @db.Decimal(10, 2)
- whiletrueCommissionRate :   Decimal         default(5.00)     @db.Decimal(10, 2)
migration-reset 시 seed 실행되면서 더미 상품홍보페이지, 상품홍보 아이템 데이터 1개 추가하도록 해두었습니다
> feat : 방송인상품홍보페이지, 상품홍보 스키마 추가

- libs/components-seller/src/lib/BusinessRegistrationForm.tsx
- libs/shared-types/src/lib/constants/signupRegisterOptions.ts
#230 
원인 : 이메일이 유효한지 확인하는 정규표현식이 @test.co.kr 와 같은 도메인을 포함하지 못함
접근 : 정규표현식 패턴으로 확인하는 대신 validate 함수에서 Joi 스키마 이용, 이메일 검증 필요한 부분(회원가입, 전자계산서발급 이메일)에 동일한 emailRegisterOptions 적용
- email regex validation으로 검색한 결과 정규표현식 자체가 너무 길고 이해하기 어려웠음
- config validation 위해 Joi 라이브러리를 이미 사용하고 있으므로 가져와서 사용함
=> 이메일 검증 필요한 부분에서 @test.co.kr 와 같은 도메인도 입력할 수 있음
> fix : 이메일 validation 방식 수정

- libs/components-seller/src/lib/OrderDetailGoods.tsx
- libs/components-seller/src/lib/OrderDetailTitle.tsx
- libs/components-shared/src/lib/SellTypeBadge.tsx
- libs/nest-core/src/lib/interceptors/http-cache.interceptor.ts
- libs/nest-modules-goods/src/goods/goods.service.ts
- 주문 상세페이지에서 주문에 대한 판매유형이 아닌 주문 내 포함된 상품별 판매유형 표시
- 판매자의 승인된 상품id 목록 조회 함수에 상품홍보(productPromotion)의 fmGoodsSeq도 추가
음바쿠님이 작업하신 바탕으로 주문 전체의 판매유형 표시하던 것에서
주문 내 포함된 상품의 판매유형 표시하는 방식으로 수정해봤습니다 
판매자 주문 조회시 자신의 상품만 확인하는 부분에서 상품홍보의 fmGoodsSeq가 조회가 안되길래 그부분도 추가하였습니다
이렇게 하면 어떨지?? 확인 부탁드립니다
> feat(seller): 판매자 - 주문 상세페이지 판매 유형 추가 #236에서 주문 내 상품별 판매유형 표시

- apps/admin/pages/live-shopping/[liveShoppingId].tsx
- libs/components-admin/src/lib/AdminGoodsConfirmationDialog.tsx
- libs/components-admin/src/lib/AdminGoodsList.tsx
- libs/nest-modules-admin/src/admin/admin.service.ts
[관리자] lc상품, 라이브쇼핑, 상품홍보의  들어가지 않도록 처리
lc상품, 라이브쇼핑, 상품홍보의 연결된 퍼스트몰 고유 상품 번호 (goodsSeq)를 입력할 때, 기존에 입력된 고유상품번호라면 입력되지 않도록 처리 필요
- project-lc 상품 검수 과정
- 라이브쇼핑 정보 수정 과정
- 상품홍보페이지 상품 등록/수정 과정 ⇒ [관리자] 방송인 상품홍보페이지 관리 에서 진행함
> feat: 퍼스트몰 상품 번호 중복입력되지않도록 처리

- libs/stores/src/lib/liveShoppingStateBoardWindowStore.tsx
#253 
현황창을 닫았을때 window객체가 null이 될거라 생각했는데
객체는 그대로 있고 객체 내부값이 {window: null, self: null, closed: true, ...} 이 됨
현황창 열때 window 객체 내부 closed 여부도 같이 확인하여
closed인 경우 새로운 window 객체로 갈아끼우도록 수정함
> [fix] 방송인센터 현황창 닫았을때 다시 안열리는 문제 수정

- libs/components-web-bc/src/lib/LiveShoppingCurrentStateBoard.tsx
#259 
해당 문제 발생 원인 : 예전에 라이브커머스 현황판 다크모드일때 텍스트 표시되지 않아 Motionbox 내부 자식 컴포넌트의 배경색을 고정했음
수정방안 : MotionBox의 variants 값에 useColorModeValue적용하여 다크모드색 적용
> [fix] 현황판 배경 깜빡임 수정

- libs/components-seller/src/lib/GoodsRegistPictureDialog.tsx
- libs/components-seller/src/lib/GoodsRegistPictureOrderChangeDialog.tsx
- libs/components-seller/src/lib/GoodsRegistPictures.tsx
- libs/components-shared/src/lib/AvatarChangeButton.tsx
- libs/hooks/src/lib/mutation/useGoodsImageMutation.tsx
- libs/hooks/src/lib/queries/useAdminLiveShoppingList.tsx
- libs/nest-modules-goods/src/goods/goods.controller.ts
- libs/nest-modules-goods/src/goods/goods.service.ts
- 사진 등록 다이얼로그에 이미지를 1:1 비율로 잘라낼 수 있는 기능 추가
- 등록된 이미지 순서 변경 다이얼로그 추가
- 기타 수정사항
- 관리자페이지 라이브쇼핑목록 조회요청 live-shopping => /admin/live-shopping 으로 수정
- 사진 등록하기 다이얼로그
- 상품사진 - 등록된 이미지 목록
- 상품 사진 순서 변경 다이얼로그
> [판매자센터 상품 등록] 사진 업로드시 이미지 1:1 비율로 잘라내는 기능, 등록한 이미지 순서변경 기능 추가

- libs/components-seller/src/lib/SettlementList.tsx
윈도우 엑셀에서 csv 파일 열었을 때 인코딩 문제로 올바르게 볼 수 없고, 유저가 매번 인코딩 변경과정을 거쳐야 함
-> data-grid의 엑셀에서 자동으로  utf8 인코딩으로 인식하도록 하는 옵션을 켬
> feat: 정산목록 csv 다운로드 인코딩 수정 - utf8

- libs/components-admin/src/lib/kkshow-main/AdminKkshowShoppingKeywords.tsx
- libs/components-web-kkshow/src/lib/shopping/ShoppingKeywords.tsx
- libs/prisma-orm/prisma/seedData/kkshowShoppingTab.ts
- libs/shared-types/src/lib/res-types/kkshowShoppingTab.res.ts
<details>
<summary>이전</summary>
</details>
<details>
<summary>이후</summary>
> fix(web-kkshow): 모바일화면에서 키워드 모음 잘려보이는 현상 수정

- docker-compose.yml
- libs/prisma-orm/prisma/migrations/20220404094900_version7/migration.sql
- libs/prisma-orm/prisma/migrations/20220406071635/migration.sql
- nrgram 적용 마이그레이션 파일 생성
- ngram 적용시, innodb_ft_min_token_size 대신 ngram_token_size 사용
- ngram_token_size 디폴트는 2
- 우리는 1로 설정 (떡, 닭, 빵) -> db의 부하는 상승한다고 합니다
> feat: nrgram 마이그레이션 파일 생성

- libs/components-seller/src/lib/MypageOrderStats.tsx
- libs/components-seller/src/lib/MypageSalesStats.tsx
- libs/hooks/src/index.ts
- libs/hooks/src/lib/queries/useSellerOrderStats.tsx
- libs/nest-modules-order/src/lib/order.controller.ts
- libs/nest-modules-order/src/lib/order.service.ts
- libs/shared-types/src/lib/constants/orderProcessStepDict.ts
GET order/stats 생성 => fm-order/stats와 동일한 형태의 데이터 리턴
주문과 환불 연결된 판매자의 상품을 기준으로 오늘 주문금액, 오늘 환불금액 표시
**테스트케이스**
사전작업
1. testseller 외에 아무 판매자나 만들고 다른 판매자에 테스트상품 2를 연결, 기존의 testseller는 상품1과 연결된 상태에서 testseller로 로그인하여 확인
2. 주문의 날짜를 다르게 지정
- 주문현황 (최근 1개월 기준 = createDate가 한달 내인 주문)
(각 기준은 기존 fm-order에서 사용하던 주문현황조회 서비스함수 getOrdersStats 참고함)
- 오늘 매출 현황
- 주문
- 환불
> [판매자] 마이페이지 홈 현황 (project-lc)

- apps/web-seller/pages/mypage/orders/[orderCode].tsx
- libs/components-seller/src/lib/kkshow-order/OrderReturnStatusDialog.tsx
- libs/components-web-kkshow/src/lib/mypage/orderList/CustomerOrderItemActionButtons.tsx
- libs/components-web-kkshow/src/lib/mypage/orderList/OrderCancelDialog.tsx
- libs/hooks/src/index.ts
- libs/hooks/src/lib/mutation/useRefundMutation.tsx
- libs/nest-modules-order/src/lib/order-cancellation/order-cancellation.controller.ts
- libs/nest-modules-order/src/lib/order-cancellation/order-cancellation.service.ts
- libs/nest-modules-refund/src/lib/refund.controller.ts
- 판매자센터 반품(환불)요청에 대해 완료처리는 진행할 수 없도록 수정(환불절차는 관리자가 진행함). 판매자는 승인까지만 진행하고, 이후 관리자가 환불 진행 후 반품완료처리됨
- 판매자센터 주문취소 요청에 대한 승인거절 과정 불필요하여 삭제(상품준비 상태 이후 주문은 반품요청 진행됨, 결제완료 단계에서는 상품이 준비되지 않았으므로 판매자 승인없이 환불처리 가능함)
- 소비자센터 주문취소시 바로 주문취소완료 처리 & 환불처리 진행하도록 수정
- 판매자센터 주문취소내역에 대한 알림표시 삭제
> 피드백반영 : 판매자 - 반품(환불) 처리, 소비자 - 주문취소

- apps/admin/pages/live-shopping/[liveShoppingId].tsx
- libs/components-admin/src/lib/AdminBroadcasterProductPromotionSection.tsx
- libs/components-admin/src/lib/AdminLiveShoppingList.tsx
- libs/components-admin/src/lib/AdminLiveShoppingUpdateConfirmModal.tsx
- libs/components-admin/src/lib/kkshow-main/AdminKkshowMainCarouselItemView.tsx
- libs/components-admin/src/lib/kkshow-main/AdminKkshowMainPreviewSection.tsx
- libs/components-seller/src/lib/LiveShoppingList.tsx
- libs/components-web-bc/src/lib/BroadcasterLiveShoppingList.tsx
- libs/firstmall-db/src/lib/fm-orders/fm-orders.controller.ts
- libs/firstmall-db/src/lib/fm-orders/fm-orders.service.ts
- libs/firstmall-db/src/lib/fm-settlements/fm-settlements.service.ts
- libs/hooks/src/lib/queries/useAdminDuplicatePromotionPageFlag.tsx
- libs/nest-modules-admin/src/admin/admin-product-promotion.controller.ts
- libs/nest-modules-admin/src/admin/admin.service.ts
- libs/nest-modules-broadcaster/src/broadcaster/broadcaster-promotion-page.service.ts
- libs/nest-modules-goods/src/goods/goods.service.ts
- libs/nest-modules-product-promotion/src/lib/product-promotion.service.ts
- libs/shared-types/src/lib/dto/broadcasterProductPromotion.dto.ts
- libs/shared-types/src/lib/dto/liveShopping.dto.ts
- (스키마)기존 연결된 fmGoodsReq를 제거하지는 않는다 (이번 배포에서)
- fmGoodsReq 연결하는 작업을 모두 제거한다
- fmGoodsReq 와 관련된 모든 사용하지 않는 작업을 deprecate 처리한다
- 관리자 - 라이브쇼핑 등록/수정
- 관리자 - 상품홍보 페이지 관리
- 관리자 - 크크쇼메인화면 관리 → 퍼스트몰 링크 → 크크쇼 goods 링크
- 220614 15:00 ~ 18:00 (3)
> [관리자] fmGoodsSeq 입력제거 처리

- apps/admin/pages/live-shopping/[liveShoppingId].tsx
- libs/components-admin/src/lib/AdminLiveShoppingBroadcasterName.tsx
- libs/components-admin/src/lib/BroadcasterAutocomplete.tsx
> fix: 방송인 닉네임 없는 경우, 라이브 쇼핑 등록시 방송인 구분 못하는 문제 수정

- libs/components-web-kkshow/src/lib/search-input/FullPageSearchBox.tsx
- libs/components-web-kkshow/src/lib/search-input/SearchInputBox.tsx
- libs/components-web-kkshow/src/lib/search-input/Searcher.tsx
- 관련 문서들 찾아봤는데, 되는 게 맞는 상황인 것으로 보이지만 안돼서 다른 추천 방법인 onClick으로 변경함
> fix: 검색창 form-id 대신 onClick으로 변경

- libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
- libs/nest-modules-goods/src/goods/goods.service.ts
- 판매자>상품등록 에서 상품 생성이후 ⇒ 해당 상품 상세보기 조회시 no data 표시됨, 크크쇼 상품페이지에서 해당 상품 조회시 상품 정보가 안뜸
상품 상세조회시 `JSON.parse(result.informationNotice?.contents as string)` 부분에서 오류발생함
원인 : 상품 생성 혹은 수정시 입력한 informationNoticeContents가 string이 아닌 객체형태로 저장되어 있어서 오류가난거같음
수정방안 : 상품 생성 혹은 수정시 informationNoticeContents 값에 JSON.stringify 적용하여 저장
**기타 수정 사항**
> fix: 상품 필수정보 생성 혹은 수정 이후 상품상세 조회 오류 발생

- apps/web-kkshow/pages/mypage/shipping-tracking/[orderCode].tsx
- libs/components-seller/src/lib/kkshow-order/OrderFilterConsole.tsx
- libs/components-web-kkshow/src/lib/mypage/order/OrderInfoExportsList.tsx
- libs/components-web-kkshow/src/lib/mypage/orderList/CustomerOrderItemActionButtons.tsx
- libs/components-web-kkshow/src/lib/mypage/orderList/CustomerOrderList.tsx
- libs/components-web-kkshow/src/lib/nonmember/NonMemberOrderDetailDisplay.tsx
- libs/nest-modules-order/src/lib/order.service.ts
- 주문상세화면에서는 선물주문인경우 출고정보 표시되지 않았음
- 소비자 > 주문/배송목록에서 '배송조회' 버튼을 눌렀을때 이동하는 배송조회화면에서 배송지와 운송장번호가 표시됨
수정내용
- 주문목록데이터 응답타입에는 출고정보가 포함되지 않기때문에 주문상세 조회시 & appType=”customer” 소비자센터에서 요청한 경우에 한해서 적용
> fix : 소비자 주문내역목록에서 선물하기 주문도 배송조회가 가능한 문제 수정

- libs/components-seller/src/lib/ExportOrderOptionList.tsx
- libs/components-seller/src/lib/kkshow-order/OrderCancelStatusDialog.tsx
- libs/components-seller/src/lib/kkshow-order/OrderList.tsx
- libs/components-seller/src/lib/kkshow-order/OrderReturnStatusDialog.tsx
- libs/components-shared/src/lib/order/ExchangeReturnCancelRequestGoodsData.tsx
- libs/components-web-kkshow/src/lib/mypage/exchange-return-cancel/detailPage/CustomerOrderCancelDetail.tsx
- libs/components-web-kkshow/src/lib/mypage/exchange-return-cancel/detailPage/CustomerReturnDetail.tsx
> fix : 버그수정 - 출고다이얼로그에 본인이 판매하지 않는 상품도 뜨는 문제 외

- libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
hotfix
상품옵션이 2~3개씩 미리 선택되어있고, 제거할수도 없는 현상. 새로고침시 올바르게 변함
옵션이 없는 상품의 경우 입장시 기본옵션이 선택되어있도록(개수 1개) 구성함. 여기서 문제가 있는 듯
미리 선택하는 기능이 반복실행되지 않도록 처리
- 기존: 기본옵션만 있는 경우 해당 기능 실행
- 수정: 기본옵션만 있는 경우 + 선택된 옵션이 없는 경우 해당 기능 실행
> fix(kkshow): 기본옵션 미리선택기능 여러번 실행 버그 수정

- apps/admin/pages/broadcaster/promotion-page/[promotionPageId].tsx
- apps/web-kkshow/pages/bc/[broadcasterId].tsx
- libs/components-admin/src/lib/AdminBroadcasterPromotionPageCreateSection.tsx
- libs/components-admin/src/lib/AdminBroadcasterPromotionPageDetail.tsx
- libs/components-admin/src/lib/AdminBroadcasterPromotionPageList.tsx
- libs/components-admin/src/lib/AdminBroadcasterPromotionPageUpdateSection.tsx
- libs/components-web-kkshow/src/lib/promotion-page/PromotionPageProfile.tsx
- libs/nest-modules-broadcaster/src/broadcaster/broadcaster-promotion-page.controller.ts
- libs/nest-modules-broadcaster/src/broadcaster/broadcaster-promotion-page.service.ts
- libs/nest-modules-broadcaster/src/broadcaster/broadcaster.controller.ts
- libs/prisma-orm/prisma/seed.ts
- libs/prisma-orm/prisma/seedData/dummyBc.ts
- libs/shared-types/src/lib/dto/broadcasterPromotionPage.dto.ts
- [크크쇼]: 관리자에 의해 상품홍보페이지 등록되지 않은 방송인 홍보페이지 생성하지않도록 구성
- [api] : 상품홍보페이지 BroadcasterPromotionPage.url이 없는 경우 `${getKkshowUrl()}/bc/${방송인아이디}` 로 등록되도록 (라이브쇼핑등록시, 상품홍보도 함께 등록하는 절차도 확인 필요)
- [관리자]: 상품홍보페이지탭 → BroadcasterPromotionPage.url이 없는 경우 `${getKkshowUrl()}/bc/${방송인아이디}` 로 보여지도록 구성
- [크크쇼]: 방송채널 링크 디자인 수정 (짧은 링크 하나만 있어도 …표시 되는 등)
- 간단한 수정사항으로 판단해 함꼐 진행함 → [관리자,API] 방송인 홍보페이지 알림말 등록/수정
- 홍보페이지
- 관리자
> [크크쇼] 방송인 홍보페이지 버그수정 + 소개글기능추가

- apps/admin/pages/live-shopping/[liveShoppingId].tsx
- apps/web-seller/pages/mypage/live/regist.tsx
- libs/components-admin/src/lib/AdminLiveShoppingList.tsx
- libs/components-core/src/lib/ChakraAutoComplete.tsx
- libs/components-seller/src/lib/LiveShoppingList.tsx
- libs/components-seller/src/lib/LiveShoppingRegistForm.tsx
- libs/components-seller/src/lib/LiveShoppingRegistManagerContacts.tsx
- libs/components-seller/src/lib/LiveShoppingRegistRequestField.tsx
- libs/components-shared/src/lib/LiveShoppingDetailDialog.tsx
- libs/nest-modules-goods/src/goods/goods.service.ts
- libs/nest-modules-liveshopping/src/live-shopping/live-shopping.service.ts
- libs/shared-types/src/lib/res-types/liveShoppingWithGoods.res.ts
- 문제 정의
소상공인은 판매자 센터에 들어오는 횟수가 적을 수록 좋다.
- 현상황 
상품을 등록하고 상품 승인되기까지 기다리다 승인되면 이후 라이브 쇼핑을 등록한다.
- 기대 효과
상품을 등록 후 바로 라이브 쇼핑을 등록할 수 있다.
- 변경 사항 
상품 승인 되지 않아도 라이브 쇼핑 등록 페이지에서 상품 선택이 가능하다.
- 판매자
- 관리자
판매자
관리자
> [판매자센터] 상품 승인되지 않아도 라이브 쇼핑 진행 요청에서 상품 선택 가능

- apps/admin/pages/admin-manage/index.tsx
- libs/hooks/src/lib/queries/useProfile.tsx
profile 요청의 catch 구문에서 에러미반환 처리
> [http] useProfile 콘솔에 401 에러메시지 뜨지 않도록 개선 (보안)

- apps/admin/pages/order/exports/[exportCode].tsx
- apps/admin/pages/order/exports/index.tsx
- apps/web-seller/pages/mypage/orders/exports/[exportCode].tsx
- libs/components-admin/src/lib/AdminOrderExportList.tsx
- libs/components-constants/src/lib/navigation.ts
- libs/components-shared/src/lib/delivery-tracking/DeliveryTracking.tsx
- libs/nest-modules-export/src/lib/export.service.ts
- libs/shared-types/src/lib/dto/kkshowExport.dto.ts
- libs/shared-types/src/lib/res-types/export.res.ts
- 현재 출고정보를 어디서도 확인할 수 없음
- 관리자에서 출고 관련된 사항들을 조회할 수 있어야 한다. ( 판매자 센터에서 등록한 출고 정보 )
- 페이지처리
- 판매자별 필터링 (모두 불러온다음 필터링 or 판매자 클릭시 해당 판매자 정보만 or …)
- 기간별 필터링
- 출고 상세 정보 조회
> feat: 출고 조회 기능 추가

- libs/components-constants/src/lib/footerLinks.ts
- libs/components-layout/src/lib/CommonFooter.tsx
네이버페이 가입 심사를 위해 푸터에 포함되어야 할 기본정보 중 크크쇼에 없는 ‘사업자정보확인버튼’ 추가
> feat: footer 사업자정보확인 기능 추가

- libs/components-shared/src/lib/delivery-tracking/DeliveryTracking.tsx
- libs/nest-modules-export/src/lib/export.service.ts
- libs/nest-modules-order/src/lib/order.service.ts
기존 코드에서는 export.sellerId로 특정 판매자의 출고정보를 조회하고 있었음
관리자 출고시 Export 데이터에 sellerId를 저장하지 않음
관리자가 출고하였으나 판매자센터에서 해당 주문에 대한 출고정보를 조회할 수 없게됨(sellerId 가 null임)
=> sellerId로 조회하는 대신, exportItems에 해당 판매자의 상품이 포함된 출고정보를 조회하도록 수정함
> fix : 판매자센터에서는 판매자 상품이 포함된 출고정보만 조회

- apps/overlay-controller/src/lib/admin.js
- 크리에이터 연결이 됐음에도 크리에이터 연결 되지 않음으로 표시 → **연결되지않음으로 표시된 경우 관리자 메시지 보내기란이 비활성화되도록 처리되어 있음**
- 관리자 메시지 보내기가 활성화 되지 않음
> fix(overlay-controller): 관리자메시지보내기란 활성화 처리 구분 제거

- libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
1. (버그 - iOS)상품 구매메시지 입력시 해당 입력창으로 줌인되고, 모두 작성이후 화면 스프레드시 다시 줌아웃되지 않음
- 상품구매 후원메시지 입력시 줌인되지 않도록 구성
> fix(kkshow): 후원메시지 입력 줌인되지 않도록 수정

- libs/components-web-kkshow/src/lib/promotion-page/PromotionPageGoodsDisplay.tsx
- libs/components-web-kkshow/src/lib/promotion-page/PromotionPageGoodsList.tsx
- libs/components-web-kkshow/src/lib/shopping/category/CategoryGoodsList.tsx
모바일화면 1개씩 보이는 것 → 2개씩
- 카테고리별 상품목록
- 방송인 홍보페이지 상품 목록
- 라이브중
- 홍보중
> improve: 상품목록 모바일 레이아웃 수정

- libs/nest-modules-kkshow-search/src/kkshow-search/kkshow-search.service.ts
홍보페이지가 설정되지 않은 방송인이 상품/라이브/방송인 등 검색결과에 포함되는 경우 이어질 URL을 가져오지 못해 검색 자체가 실행이 되지 않는 오류.
→ 상품 검색시 상품에 연결된 라이브쇼핑을 내부적으로 조회하여, 해당 라이브쇼핑에 연결된 방송인을 방송인 검색결과 목록에 채워넣는데, 이 과정 중 라이브쇼핑에 연결되었으나 홍보페이지가 설정되지않은 방송인이 있는 경우 문제가 발생
→ 현재 라이브쇼핑 등록시 홍보페이지가 자동으로 생성되도록 구성되어 있으므로 앞으로는 이 문제가 발생하지 않을 것임.
→ 이 문제는 라이브쇼핑 등록시 홍보페이지 자동 생성 기능이 구현되기 이전에 라이브쇼핑을 진행한 방송인이 존재하여 생기는 오류.
⇒ 처리방안: **방송인 홍보페이지 URL이 없으면 방송인 검색결과에 포함되지 않도록 한다.**
> fix(kkshow): 홍보페이지 없는 경우 방송인 검색결과 목록 미반영 처리

- libs/components-admin/src/lib/AdminLoginForm.tsx
- libs/components-shared/src/lib/LoginForm.tsx
- 서버에 의한 로그인 실패시에만 “잠시후 다시로그인”
- 로그인정보가 틀린 경우에는 “가입하지 않은 아이디이거나, 잘못된 비밀번호입니다.”
> fix: 로그인에러 올바르게 보여지도록 수정

- apps/admin/pages/customer/coupon/[couponId].tsx
- apps/admin/pages/customer/coupon/index.tsx
- libs/hooks/src/lib/queries/useAdminCoupon.tsx
- 관리자 쿠폰관리 > 고객목록란이 올바르게 표시되지 않음
- 추가 작업: 쿠폰 목록에서 특정 쿠폰 관리로 들어갔을 때, 어떤 쿠폰 관리 페이지에 들어온 건지 구분할 수없음
> fix(admin): 쿠폰고객목록 조회 수정 + 브레드크럼추가

- libs/components-seller/src/lib/kkshow-order/OrderFilterConsole.tsx
- libs/components-seller/src/lib/kkshow-order/OrderList.tsx
- libs/nest-modules-order/src/lib/order.service.ts
- ‘취소요청’ 상태의 주문이 ‘결제확인’ 필터에 포함됨 => 취소요청, 반품요청, 교환요청의 경우 주문/주문상품옵션의 상태가 아님
- 이 세 경우가 포함되는 주문은 주문의 기존 상태 + 해당 상태를 같이 보여주는 방식으로 수정
**테스트케이스**
- 주문 상태가 ‘출고완료' 이고 해당 주문에 대해 소비자가 ‘환불요청’을 한 경우
- 주문목록에서 판매자의 상품이 포함된 취소요청, 반품요청, 교환요청이 있는 경우에만 배지를 표시한다
- 판매자1의 상품, 판매자2의 상품을 함께 구매(주문A) ⇒ 판매자2의 상품만 환불요청 한 경우
> fix(seller) : 주문목록 필터링 - 취소요청, 환불요청, 교환요청 배지 표시 

- libs/components-shared/src/lib/CouponBadge.tsx
- libs/components-web-kkshow/src/lib/mypage/benefits/Benefits.tsx
- libs/components-web-kkshow/src/lib/mypage/benefits/CustomerCouponHistoryList.tsx
- libs/components-web-kkshow/src/lib/mypage/benefits/CustomerCouponList.tsx
- libs/components-web-kkshow/src/lib/payment/Discount.tsx
- libs/utils-frontend/src/lib/checkCouponAvailable.ts
- 혜택관리 페이지 문구 수정
- 보유쿠폰 => 사용 가능한 쿠폰
- 보유 쿠폰목록 => 사용 가능한 쿠폰목록
- 쿠폰 사용내역 => 쿠폰 변동 내역
- 발급된 쿠폰의 유형 : '적립' => '발급'
- 마이페이지 보유쿠폰 목록과 결제페이지 쿠폰목록에서 사용했거나, 기간이 지난 쿠폰은 표시되지 않도록 수정함
- 결제페이지에서 쿠폰 적용시 결제금액이 올바르게 표시되지 않는 문제는 동일한 현상이 발생하지 않아 조치를 취하지 않음
- 결제페이지에서 쿠폰 적용시 퍼센트 할인쿠폰의 할인율이 할인금액으로 들어가는 문제 수정
**테스트 케이스**
> fix(kkshow) : 사용한 쿠폰도 보유쿠폰에 표시되는 버그 수정

- apps/web-kkshow/pages/mypage/info.tsx
- libs/components-shared/src/lib/GoogleLoginButton.tsx
- libs/components-shared/src/lib/KakaoLoginButton.tsx
- libs/components-shared/src/lib/LoginForm.tsx
- libs/components-shared/src/lib/NaverLoginButton.tsx
- libs/components-shared/src/lib/PasswordCheckForm.tsx
- libs/components-shared/src/lib/signup/SignupForm.tsx
- libs/components-web-kkshow/src/lib/KkshowNavbar.tsx
- libs/components-web-kkshow/src/lib/cart/CartActions.tsx
- libs/components-web-kkshow/src/lib/goods/GoodsInquiryFormDialog.tsx
- libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
- libs/hooks/src/index.ts
- libs/hooks/src/lib/useNextpageUrlParam.tsx
- libs/nest-core/src/lib/middlewares/socialLoginUserType.middleware.ts
- libs/nest-modules-auth/src/social/social.controller.ts
- libs/prisma-orm/prisma/migrations/20220819051912_/migration.sql
- libs/prisma-orm/prisma/migrations/20220819053840_/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/shared-types/src/index.ts
- libs/shared-types/src/lib/constants/nextpageParamKey.ts
크크마켓에서 현재 라이브 판매중인 상품을 찾기 어려움
- 채팅링크클릭 → 상품페이지 → 옵션선택 → 메시지 작성 → 구매 → 회원가입필요 → 회원가입진행 → 크크마켓메인으로 이동되어 다시 라이브중인 상품을 찾아들어가야 하는데, 크크마켓에서는 찾을 수 없음. → 다시 방송화면으로 돌아가 채팅링크 클릭 → 구매
1. 회원가입 이후 이동될 페이지 기능 추가
- 현재 회원가입 이후 고정적으로 크크쇼 메인으로 이동되도록 구성되어있음.
- 회원가입 이후 필요한 페이지로 이동할 수 있는 기능 추가 필요 (상품구매 → 회원가입 루트로 넘어왔다면 구매페이지로 이동)
2. ~~크크쇼메인 또는 크크마켓메인에 라이브쇼핑 진행중인 상품으로 이동될 수 있는 링크를 구성~~
1. 테스트 시나리오1: 상품페이지 → 주문 → 이메일 회원가입
2. 테스트 시나리오2: 상품페이지 → 주문 → 소셜 회원가입
1. 구글
2. 네이버
3. 카카오
> [크크쇼] 라이브상품 페이지로의 접근성 개선

- libs/components-shared/src/lib/signup/SignupForm.tsx
- libs/nest-modules-customer/src/lib/customer.controller.ts
- libs/nest-modules-customer/src/lib/customer.service.ts
- libs/shared-types/src/lib/dto/signUp.dto.ts
- 이름을 닉네임처럼 입력함
- 주문시 닉네임을 입력하지 않음
- 이름(본명)
- 닉네임(후원메시지에 표시)
- ‘김크크쇼’(닉네임같은 이름)를 ‘홍길동’으로 변경
- 이름 밑에 닉네임을 입력할 수 있도록한다. (이름과 닉네임을 구분한다.)
- 닉네임은 선택사항
- 닉네임과 이름을 헷갈리지 않도록
> feat(kkshow): 회원가입시 닉네임 입력 추가

- libs/components-web-kkshow/src/lib/goods/GoodsViewPurchaseBox.tsx
- libs/components-web-kkshow/src/lib/payment/OrderItemSupport.tsx
- libs/components-web-kkshow/src/lib/payment/OrderPaymentForm.tsx
- libs/components-web-kkshow/src/lib/payment/ReceiptOrderItemInfo.tsx
- libs/stores/src/lib/goodsViewStore.tsx
- 구매메시지 입력시 닉네임을 입력할수 있는 입력칸 추가
- 닉네임이 없는 상태에서 입력된 닉네임은 계정의 기본닉네임으로 설정됨
- 닉네임이 있는 상태에서는 구매메시지 닉네임칸에 기본적으로 작성되어있도록 구성
- 닉네임이 있어도 구매메시지에 입력한 닉네임으로 응원메시지 송출되도록 구성
- 비회원도 닉네임 입력 가능
- front: 상품상세페이지
- front: 구매페이지(결제페이지)
- front: 주문완료페이지
- back: 장바구니 처리
- back: 구매 처리
- 상품상세페이지
- 구매페이지(결제페이지)
- 주문완료페이지
- 장바구니담기시 닉네임 처리
- 구매시 닉네임처리
> feat: 후원메시지 닉네임 설정 추가 + 최초닉네임설정

- libs/components-shared/src/lib/PasswordChangeForm.tsx
- libs/components-shared/src/lib/ResetPasswordForm.tsx
비밀번호 재설정 페이지에서 사용하는 비밀번호 입력폼은 다른 컴포넌트(PasswordChangeDialog)에서도 사용중임
다른 컴포넌트에는 sumit 버튼이 있으나 비밀번호 재설정페이지에는 해당 버튼이 없어서 비밀번호 재설정을 할 수 없었음
submit 버튼을 추가하여 비밀번호 재설정페이지에서도 비밀번호를 변경할 수 있도록 수정함
> fix(common) : resetPassword 페이지 폼 전송버튼 추가

- apps/admin/pages/order/list/[orderId].tsx
- libs/components-admin/src/lib/AdminOrderList.tsx
관리자가 주문목록/주문상세페이지에서 주문이 선물 주문인지 여부를 판단할 수 없다.
- 관리자 주문목록, 주문상세
- 선물여부 보여지도록 구성
> feat: 관리자 주문목록/주문상세 선물 여부 조회 기능

- libs/nest-modules-auth/src/social/social.service.ts
- libs/nest-modules-auth/src/social/strategy/google.strategy.ts
- libs/nest-modules-auth/src/social/strategy/kakao.strategy.ts
- libs/nest-modules-auth/src/social/strategy/naver.strategy.ts
소셜로그인시 정보 제공 동의를 받지만 사적인 프로필사진을 크크쇼 프로필사진으로 등록하는 것은 이상하다
> feat: 소셜로그인시 프로필 사진 기본 등록 제거처리

- apps/overlay-controller/src/lib/admin.js
- apps/overlay/src/lib/overlayClient.js
- libs/components-web-kkshow/src/lib/payment/OrderItemSupport.tsx
- libs/components-web-kkshow/src/lib/payment/OrderPaymentForm.tsx
- libs/components-web-kkshow/src/lib/payment/Payment.tsx
- libs/nest-modules-order/src/lib/order.service.ts
- libs/nest-modules-overlay/src/overlay/overlay.controller.ts
- libs/nest-modules-overlay/src/overlay/overlay.message.gateway.ts
- libs/nest-modules-overlay/src/overlay/overlay.service.ts
- libs/prisma-orm/prisma/schema.prisma
- libs/prisma-orm/prisma/seedData/kkshowSubNav.ts
- libs/shared-types/src/lib/overlay-controller/overlay-controller-types.ts
- libs/shared-types/src/lib/overlay/overlay-types.ts
1. 회원가입을 했지만 닉네임을 설정하지 않은 경우 ‘’(공백)으로 응원메시지와 구매랭킹이 뜬다.
1. 닉네임이 등록되지 않은 경우 응원메시지 및 구매랭킹에 포함시키지 않는다. (비회원 구매로 간주) = 후원 메시지 입력시 닉네임을 입력받으므로, 비회원 메시지 구분을 “비회원 주문인지 아닌지” 로 판단하지 않고 닉네임/메시지가 있는지 없는지로 판단하도록 수정
**비회원주문인지 여부가 아닌, 닉네임/메시지가 작성되었는 지 여부에 따라 메시지 유형을 구분하도록 수정**
- 닉네임X, 메시지X의 경우
- 닉네임O, 메시지X의 경우
- 닉네임X, 메시지O의 경우
- 닉네임O, 메시지O의 경우
- 닉네임X, 메시지X의 경우
- 닉네임O, 메시지X의 경우
- 닉네임X, 메시지O의 경우
- 닉네임O, 메시지O의 경우
> [크크쇼] 구매메시지 개선

- libs/components-constants/src/lib/footerLinks.ts
- libs/nest-modules-mail/src/lib/templates/createInactivateNoticeTemplate.ts
기존 : 2019-부산금정-0581
변경 : 2022-부산연제-0281
> feat: 통신판매업신고번호 수정

- apps/admin/pages/customer/coupon/[couponId].tsx
- libs/components-web-kkshow/src/lib/payment/Discount.tsx
- libs/nest-modules-coupon/src/lib/coupon.controller.ts
- libs/nest-modules-coupon/src/lib/coupon.service.ts
- libs/shared-types/src/lib/dto/customerCoupon.dto.ts
전체 상품에 적용가능한 쿠폰이 생성시점의 전체 상품들에만 사용가능하고, 쿠폰 생성 시점 이후에 생성된 새로운 상품들에는 사용이 불가능하도록 처리되어 있음.
- 전체상품에 사용가능한 쿠폰은 상품과 연결시키지 않고, 모든 상품 주문시 사용할 수 있도록 구성
비개발자가 테스트할 사항은 없음.
> feat: 쿠폰등록시 전체상품용 쿠폰은 상품 연결하지 않도록 구성

- libs/components-web-kkshow/src/lib/goods/GoodsViewMeta.tsx
- 라이브특가가설정되지 않아도 후원 방송인 선택시 LIVE특가가 보여져, 빈배열을 Math.min(…) 하여 Infinity 값으로 특가가 계산됨
> fix: 라이브쇼핑 특가 설정 없는 경우 특가 표시하지않도록 수정

- libs/nest-modules-auth/src/social/social.service.ts
- libs/nest-modules-auth/src/social/strategy/naver.strategy.ts
- package.json
- yarn.lock
- passport-naver는 6년전 모듈로, 업데이트되지 않고 있음.
- 몇 가지 필드명 변경사항에 대해 작업해두지 않음
- 이를 passport-oauth2를 통해 직접 구현하도록 구성
사용자의 실명이 이름으로 설정되는 것이 올바를 것.
- 네이버에서는 제공되고 있다고 표시됨. 근데 이름 데이터가 전달되지 않는 것으로 확인됨 why?
사용하고 있는 passport 모듈 passport-naver 는 6년전 패키지로 네이버로그인API 최신 변경사항을 따르지 않고 있음
최신 개발가이드에서 제공하는 oauth2 인증 방식대로 네이버 소셜 로그인 자체적으로 구현
220824 14:00 ~ 15:00 (1)
> fix: 네이버 로그인 최신 개발 가이드에 따르도록 수정

- libs/components-web-kkshow/src/lib/payment/DeliveryAddressList.tsx
- libs/components-web-kkshow/src/lib/payment/OrderPaymentForm.tsx
- libs/components-web-kkshow/src/lib/payment/Payment.tsx
- libs/hooks/src/lib/mutation/useCustomerAddressMutation.tsx
+ 배송지에서 폰번 올바르게 불러오지 못하는 현상 수정
처음 입력한 배송지가 자동으로 기본배송지로 설정되지 않아 마이페이지에서 구매마다 새로 입력하여야 함
배송지 입력은 마이페이지에서 가능하므로 자동으로 불러오도록 하려면 마이페이지로 이동해 등록해야하는 번거로움이 있음
라이브쇼핑시 1회성으로 사용하는 크크쇼 특성상 마이페이지를 들리거나 하도록 구성하는 것 보다 자동 처리가 더 편할 것
1. 로그인한 경우 + 주소(배송지)가 하나도 없는 경우 + 직접입력한 주소가 기본배송지로 자동 등록되도록 구성.
2. 배송지 등록을 구매페이지에서 진행할 수 있도록 한다.
> [크크쇼] 첫 입력주소 자동 기본배송지

- libs/components-web-kkshow/src/lib/mypage/benefits/CustomerCouponApplyGoodsList.tsx
- libs/components-web-kkshow/src/lib/mypage/benefits/CustomerCouponDetailDialog.tsx
- libs/components-web-kkshow/src/lib/mypage/benefits/CustomerCouponList.tsx
- libs/nest-modules-coupon/src/lib/customer-coupon.service.ts
- libs/shared-types/src/lib/res-types/coupon.res.ts
크크쇼>쇼핑>혜택관리
쿠폰 적용대상이 선택 상품인 경우 선택상품 or 상세정보 클릭 시 적용 대상인 상품을 볼 수 있는 팝업창이 뜬다.
상품이미지 + 상품명 + 상품링크
상품 클릭 시 해당 상품 페이지로 이동
**테스트케이스**
> improve : [크크쇼] 마이페이지 혜택관리 개선사항

- apps/web-kkshow/pages/mypage/notice.tsx
- libs/components-admin/src/lib/AdminNoticeDialog.tsx
- libs/components-admin/src/lib/AdminNoticeSection.tsx
- libs/components-constants/src/lib/footerLinks.ts
- libs/components-constants/src/lib/navigation.ts
- libs/components-shared/src/lib/MypageNoticeSection.tsx
- libs/hooks/src/lib/queries/useNotice.tsx
- libs/nest-modules-notice/src/notice/notice.controller.ts
- libs/nest-modules-notice/src/notice/notice.service.ts
- libs/prisma-orm/prisma/migrations/20220830054342_/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/shared-types/src/lib/dto/post.dto.ts
api
- Notice 테이블에 target 컬럼 추가(전체, 판매자, 방송인, 소비자)
- 공지사항 목록 조회시 appType에 따라 해당하는 type의 글만 조회하도록 수정함
소비자
- 마이페이지 공지사항 탭 추가, target='all' | 'customer'인 공지사항 목록 표시
공통
- 푸터링크에 노션 공지사항 페이지 링크 추가
**테스트케이스**
> feat : 공지사항 링크 추가

- apps/admin/pages/customer/coupon/[couponId].tsx
- libs/components-admin/src/lib/AdminOrderExportList.tsx
- libs/hooks/src/lib/mutation/useDelieveryMutation.tsx
- libs/nest-modules-delivery/src/lib/delivery.controller.ts
- libs/nest-modules-delivery/src/lib/delivery.service.ts
- libs/shared-types/src/lib/dto/delivery.dto.ts
- libs/stores/src/index.ts
- libs/stores/src/lib/adminOrderExportListStore.tsx
여러개의 출고 목록을 한번에 배송중 배송 완료 등으로 변경할 수 있다. 
- Front
- API
> feat: 출고 상태 배송중/배송완료로 일괄 변경 처리

- apps/web-kkshow/next.config.js
- libs/components-core/src/lib/ChakraNextImage.tsx
- libs/components-shared/src/lib/goods-review/ReviewList.tsx
- libs/components-shared/src/lib/goods/GoodsDisplay2.tsx
- libs/components-web-kkshow/src/lib/EventPopup.tsx
- libs/components-web-kkshow/src/lib/GoodsDisplay.tsx
- libs/components-web-kkshow/src/lib/goods/GoodsViewMeta.tsx
- libs/components-web-kkshow/src/lib/main/carousel/KkshowMainCarouselContents.tsx
- libs/components-web-kkshow/src/lib/shopping/ShoppingCarousel.tsx
- libs/components-web-kkshow/src/lib/shopping/ShoppingCategories.tsx
- libs/components-web-kkshow/src/lib/shopping/ShoppingGoodsOfTheWeek.tsx
- libs/prisma-orm/prisma/seedData/kkshowShoppingTab.ts
네트워크 성능을 제한한 채 페이지 로딩시, 빠르게 화면을 확인할 수 없음
+느리다는 제보가 있음
1. chakra Image 컴포넌트 → next/image 로 변경하면 빨라지려나>?
2. 이미지가 화면에 안보일 때 레이지로딩 적용
3. (크크쇼 메인화면 twitch/youtube 임베드 불러오는 데에 시간이 많이 걸릴 수도)
- 내용
Nextjs 의 Image Optimization 을 위한 컴포넌트.
- **Required Props**
- src: 정적 이미지 (statically imported image) 또는 이미지 URL (path string, can be external URL or internal path depending on loader) extenralURL을 사용한다면, next.config.js 에 domains 에 명시해야 한다.
- width, height: `layout` 속성에 따라 성격이 달라지는 속성으로, 이미지의 너비(width)와 높이(height)를 표현
- `layout=intrinsic`(default) or `layout=fixed`: rendered width/height in pixels. how large the image appears.
- `layout=responsive` or `layout=fill`: original width/height in pixels. only affect the aspect ratio.
- `layout=fill` 인 경우, width/height 속성은 옵셔널이다.
- **Optional Props**
- layout …
> [성능개선] 이미지 불러오는 데에 시간이 많이 걸림

- apps/overlay-controller/src/lib/admin.js
- apps/overlay-controller/src/views/index.hbs
- 문제
- 라이브 쇼핑 시작 및 종료 시간 설정이 제대로 되었는지 알수가 없음
- 해결 방안
- 설정한 시간이 오른쪽에 뜨도록 한다.
> feat(overlay-controller): 전송된 시간 보여주기 추가

- libs/components-web-kkshow/src/lib/main/KkshowMainBestBroadcaster.tsx
- libs/components-web-kkshow/src/lib/search/GoodsCard.tsx
- 정사각형 형태의 이미지가 아닌 경우 이상하게 표시됨 => Avatar 컴포넌트 width, height 고정
- 검색결과 상품이미지 마우스 올렸을때 이미지 하얗게 되는 현상 임시 수정
> hotfix : 크크쇼 메인 하단 베스트방송인 이미지 크기가 안맞는 현상 수정

- apps/overlay/src/assets/layout.css
- apps/overlay/src/lib/overlayClient.js
- 중간금액 뉴스속보 메세지 송출시 표시되는 하단메시지(구매자들 닉네임) 속도 고정함 - 초당 150px 이동
**테스트케이스**
(송출 프로그램obs을 켜서 오버레이 브라우저 띄운 상태로 테스트함. 브라우저에서 오버레이 접속하여 테스트시 유저 동작없이 play()를 할 수 없다는 오류가 간헐적으로 발생하여 소리가 나지 않음. 이에 대한 해결방법은 아직 찾지 못함)
- “하단메시지 없이 & 뉴스속보 소리 없이” 뉴스메시지만 전송하고 싶은 경우 테마선택 위 ‘뉴스메시지 전송' 기능을 사용하면 됨
> improve : [오버레이] 중간금액 - 뉴스테마 송출 시 하단 메시지 속도 조절

- apps/web-kkshow/pages/index.tsx
- libs/components-core/src/lib/ChakraNextImage.tsx
- libs/components-web-kkshow/src/lib/EventPopup.tsx
- libs/components-web-kkshow/src/lib/GoodsDisplay.tsx
- libs/components-web-kkshow/src/lib/GoodsReviewDisplay.tsx
- libs/components-web-kkshow/src/lib/promotion-page/PromotionPageGoodsDisplay.tsx
- libs/components-web-kkshow/src/lib/search/GoodsCard.tsx
상품에 마우스를 올렸을 때 이미지가 확대대는 효과 되돌리기 위해 
해당 효과가 필요한 컴포넌트에만 framer motion 제거하고, mouseEnter이벤트 발생 시 NextImage의 style을 변경하도록 함
**기타 수정사항**
- 추석이벤트 팝업 컴포넌트 제거함
**테스트케이스**
> improve : [크크쇼] 상품 마우스 올렸을때 이미지 효과 되돌리기

- libs/components-web-bc/src/lib/OverlayUrlCard.tsx
- 문제 상황
- 한글 도메인인 경우 브라우저에서 변환해 주지만 프릭샷에서는 정상적으로 작동하지 않는 것으로 보인다.
- 해결 방안
- ‘라이브 쇼핑 URL 복사’시 한글 도메인이 아닌 변환된 URL을 복사 하도록 한다.
- ex)
- `크크쇼.com` X
- `xn--hp4b17xa.com` O
> fix: 오버레이URL 올바르게 복사되도록 수정

- libs/components-web-bc/src/lib/PromotionPageUrlCard.tsx
- 상품 홍보 페이지 이미지 수정
→ 현재 구현된 상품 홍보페이지 이미지로 변경
> improve: 홍보페이지 설명 이미지 크기 수정

- apps/admin/pages/broadcaster/settlement.tsx
- libs/components-admin/src/lib/ExternalLiveShoppingBcSettlement.tsx
- libs/components-core/src/lib/ChakraAutoComplete.tsx
- libs/components-core/src/lib/ConfirmDialog.tsx
- libs/components-web-bc/src/lib/BcSettlementHistory.tsx
- libs/hooks/src/index.ts
- libs/hooks/src/lib/mutation/useCreateSettlementBcWithExternalItem.tsx
- libs/nest-modules-admin/src/admin/admin.controller.ts
- libs/nest-modules-broadcaster/src/broadcaster/settlement-history/broadcaster-settlement-history.service.ts
- libs/nest-modules-liveshopping/src/live-shopping/live-shopping.service.ts
- libs/prisma-orm/prisma/migrations/20220916072830_/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/prisma-orm/prisma/seed.ts
- libs/shared-types/src/lib/dto/createBroadcasterSettlementHistory.dto.ts
- libs/shared-types/src/lib/res-types/liveShoppingWithGoods.res.ts
- 외부상품 판매 라이브쇼핑을 진행했던 방송인에게 정산내역을 표시하기 위해 관리자가 직접 정산내역을 생성할 수 있다
**테스트케이스**
- 관리자 센터
- 다이얼로그
- 방송인센터
> feat : [관리자] 외부상품으로 진행한 라이브쇼핑의 방송인 정산내역 생성

- apps/overlay-controller/src/lib/admin.js
- apps/web-broadcaster-center/pages/mypage/live/state/[liveShoppingId].tsx
- libs/components-web-bc/src/lib/LiveShoppingCurrentStateBoard.tsx
- libs/hooks/src/lib/subscription/useLiveShoppingStateSubscription.tsx
- libs/hooks/src/lib/useCountdown.tsx
- libs/nest-modules-liveshopping/src/live-shopping/live-shopping-state.gateway.ts
- libs/shared-types/src/lib/event-types/live-shopping-state.event-type.ts
실시간 현황판에 '라이브 종료하기' 버튼 추가
현황판에서 오버레이 컨트롤러로 아웃트로 송출 이벤트 발생 
-> 이 때 컨트롤러에서는 기존에 존재하는 오버레이 아웃트로 송출 이벤트를 발생하는 방식으로 동작함
**테스트케이스**
> feat : [방송인 - 실시간 현황판] 라이브 종료 버튼

- apps/web-kkshow/pages/bc/[broadcasterId].tsx
- libs/components-admin/src/lib/live-shopping/AdminLiveShoppingRegist.tsx
- libs/components-web-kkshow/src/lib/promotion-page/PromotionPageVideoList.tsx
- libs/nest-modules-liveshopping/src/live-shopping/live-shopping.service.ts
- libs/prisma-orm/prisma/migrations/20220923015552_/migration.sql
- libs/prisma-orm/prisma/schema.prisma
- libs/shared-types/src/lib/dto/liveShopping.dto.ts
크크쇼 방송인홍보페이지의 라이브방송 탭 활성화
방송인이 진행한 라이브쇼핑 중 유튜브영상이 등록된 경우 해당 유튜브영상을 표시함
**테스트케이스**
> feat : [크크쇼-방송인 홍보페이지] 방송내역

- apps/overlay-controller/src/lib/admin.js
- libs/nest-modules-order/src/lib/order.service.ts
- libs/nest-modules-overlay/src/overlay/overlay.screen.gateway.ts
- libs/nest-modules-overlay/src/overlay/overlay.service.ts
- libs/shared-types/src/lib/overlay/overlay-types.ts
- 랭킹 계산 시, 라이브커머스 기준이 아닌, 방송인 기준으로 구매데이터를 조회하고 있었음
=> 라이브커머스 별로 랭킹을 표시하도록 수정함
- 기타 수정사항 : 주문 시 비회원구매 여부 저장하는 코드 빠진거 추가
> fix : [오버레이] 랭킹 예전데이터 표시되는 문제 수정

- libs/components-admin/src/lib/SettlementTargetList.tsx
- libs/components-seller/src/lib/ExportBundleDialog.tsx
- libs/components-seller/src/lib/ExportDialog.tsx
- libs/components-seller/src/lib/ExportManyDialog.tsx
- libs/components-seller/src/lib/kkshow-order/ReExportDialog.tsx
원인 : 
정산대상목록(Export 출고데이터)에 sellerId 값이 없는 경우 연결된 판매자의 상점명을 표시할 수 없어서 오류가 났음
해결방안:
- seller?.sellerShop 과 같이 해당 값이 있는 경우에만 표시하도록 수정함
- 판매자센터에서 판매자가 출고를 처리했든, 관리자가 출고를 처리했든 상관없이 해당 상품의 판매자를 출고데이터의 sellerId 값으로 저장함
> fix : [관리자] 정산 탭 눌렀을때 client 오류

- libs/components-web-kkshow/src/lib/main/carousel/KkshowMainCarouselHeader.tsx
- libs/components-web-kkshow/src/lib/search-input/Searcher.tsx
- libs/components-web-kkshow/src/lib/search/SearchPageLayout.tsx
- 최초 검색시 검색결과가 있음에도 표시되지 않는 문제가 있어서 router로 페이지 이동 후 invalidation 실행하도록 코드 위치 수정함
- [크크쇼 메인 캐러셀] 문구 수정
> refactor : 검색 쿼리 invalidation 하는 코드 이동

- libs/components-admin/src/lib/AdminOrderList.tsx
- libs/components-seller/src/lib/kkshow-order/OrderListDownloadDialog.tsx
- libs/shreadsheet/src/spreadsheet/orderSpreadSheetGenerator.ts
- 관리자 주문 내보내기 버튼 두개라 헷갈림 mui datagrid 내장 내보내기 버튼 삭제
- 주문 내보내기 툴바는 관리자, 판매자 두 앱에서 사용됨. 로그인한 사용자 타입이 판매자인 경우에만 sellerId를 보내서, 주문에 포함된 해당 판매자의 상품만 조회하도록 수정함
> fix : 관리자 주문 내보내기 시 빈 파일 다운되는 현상 수정

- libs/components-seller/src/lib/ShippingOptionIntervalApply.tsx
- libs/components-shared/src/lib/shipping/ShippingPolicySetListItem.tsx
- libs/nest-modules-coupon/src/lib/customer-coupon.service.ts
- libs/prisma-orm/prisma/schema.prisma
- libs/utils-frontend/src/lib/getShippingOptionLabel.ts
- libs/utils/src/lib/calculateShippingCost.ts
- 적용가능한 배송비 옵션 구하는 로직 수정
- 배송비표시 - 구간반복 배송옵션의 글자가 '~당'으로 표시되지 않고 '~미만'으로 표시되는 문제 해결
- 배송비옵션 생성 - 구간반복 옵션 최소값 1로 수정
- 회원가입 쿠폰 - 관리자가 생성한 동일한 이름의 다른 회원가입 쿠폰이 있다면 최신에 만든 회원가입 쿠폰을 발급하도록 수정
> fix : v1.7.3 배포 이후 에러 수정

- libs/hooks/src/lib/mutation/useOrderPurchaseConfirmMutation.tsx
문제상황 : 크크쇼 소비자 주문목록에서 구매확정을 해도 구매확정주체가 admin으로 찍힘
해결방법 : 크크쇼에서 소비자가 구매확정 누르는 경우에만 customer로 값 전달
> fix : 구매확정 요청 dto에 buyConfirmSubject 값 추가
